# --------------------------------------------------------------------------------
# ----------------------------------- MC8_SCFBF -----------------------------------
# -------------------- Generated by: MRFHelper (Version 2.0) ---------------------
# ------------------ (https://github.com/WenchenLie/MRFModeler) ------------------
# --------------------------------------------------------------------------------

import os
import numpy as np
from pathlib import Path
import openseespy.opensees as ops
from subroutines.BeamHinge import BeamHinge
from subroutines.ColumnHinge import ColumnHinge
from subroutines.PanelZone import PanelZone
from subroutines.Spring_Zero import Spring_Zero
from subroutines.Spring_Rigid import Spring_Rigid
from subroutines.TimeHistorySolver import TimeHistorySolver
from subroutines.PushoverAnalysis import PushoverAnalysis
from subroutines.CyclicPushover import CyclicPushover
from subroutines.DisplayModel2D import DisplayModel2D
from Brace.brace_pairs import define_smadb_brace_pairs
from math import pi
from typing import Literal


def run_openseespy(
    maxRunTime: float,
    analysis_type: Literal["TH", "PO", "CP"],
    ShowAnimation: Literal[True, False],
    MPCO: Literal[True, False],
    MainFolder: Path,
    GMname: str,
    SubFolder: Path,
    GMdt: float,
    GMpoints: int,
    GMduration: float,
    FVduration: float,
    EqSF: float,
    GMFile: Path,
    maxRoofDrift: float,
    CollapseDrift: float,
    RDR_path: list[float],
    ):

    ops.wipe()
    ops.model("basic", "-ndm", 2, "-ndf", 3)

    # Basic model variables
    GMFile = GMFile.absolute().as_posix()

    # Results folders
    if not MainFolder.exists():
        os.mkdir(MainFolder)
    if not (MainFolder/SubFolder).exists():
        os.mkdir(MainFolder/SubFolder)

    # Basic parameters
    NStory = 8
    NBay = 3
    E = 206000.00
    mu = 0.3
    fy_beam = 345.00
    fy_column = 345.00
    ops.uniaxialMaterial("Elastic", 9, 1.e-9)
    ops.uniaxialMaterial("Elastic", 99, 1.e12)
    ops.geomTransf("Linear", 1)
    ops.geomTransf("PDelta", 2)
    ops.geomTransf("Corotational", 3)
    A_Stiff = 1.e8
    I_Stiff = 1.e13

    # Building geometry
    Floor1 = 0.0
    Floor2 = 5500.0
    Floor3 = 9800.0
    Floor4 = 14100.0
    Floor5 = 18400.0
    Floor6 = 22700.0
    Floor7 = 27000.0
    Floor8 = 31300.0
    Floor9 = 35600.0
    story_height = [5500, 4300, 4300, 4300, 4300, 4300, 4300, 4300]

    Axis1 = 0.0
    Axis2 = 9150.0
    Axis3 = 18300.0
    Axis4 = 27450.0
    Axis5 = 36600.0

    HBuilding = 35600.0


    # ------------------------------------ Nodes -------------------------------------

    # Support nodes
    ops.node(10010100, Axis1, Floor1)
    ops.node(10010200, Axis2, Floor1)
    ops.node(10010300, Axis3, Floor1)
    ops.node(10010400, Axis4, Floor1)
    ops.node(10010500, Axis5, Floor1)
    
    # Leaning column grid nodes
    ops.node(10020500, Axis5, Floor2)
    ops.node(10030500, Axis5, Floor3)
    ops.node(10040500, Axis5, Floor4)
    ops.node(10050500, Axis5, Floor5)
    ops.node(10060500, Axis5, Floor6)
    ops.node(10070500, Axis5, Floor7)
    ops.node(10080500, Axis5, Floor8)
    ops.node(10090500, Axis5, Floor9)
    
    # Leaning column connected nodes
    ops.node(10020502, Axis5, Floor2)
    ops.node(10020501, Axis5, Floor2)
    ops.node(10030502, Axis5, Floor3)
    ops.node(10030501, Axis5, Floor3)
    ops.node(10040502, Axis5, Floor4)
    ops.node(10040501, Axis5, Floor4)
    ops.node(10050502, Axis5, Floor5)
    ops.node(10050501, Axis5, Floor5)
    ops.node(10060502, Axis5, Floor6)
    ops.node(10060501, Axis5, Floor6)
    ops.node(10070502, Axis5, Floor7)
    ops.node(10070501, Axis5, Floor7)
    ops.node(10080502, Axis5, Floor8)
    ops.node(10080501, Axis5, Floor8)
    ops.node(10090502, Axis5, Floor9)
    
    # Moment frame column nodes
    ops.node(10010101, Axis1, Floor1)
    ops.node(10010201, Axis2, Floor1)
    ops.node(10010301, Axis3, Floor1)
    ops.node(10010401, Axis4, Floor1)

    ops.node(10020102, Axis1, Floor2 - 612.14/2)
    ops.node(10020202, Axis2, Floor2 - 612.14/2)
    ops.node(10020302, Axis3, Floor2 - 612.14/2)
    ops.node(10020402, Axis4, Floor2 - 612.14/2)

    ops.node(10020101, Axis1, Floor2 + 612.14/2)
    ops.node(10020201, Axis2, Floor2 + 612.14/2)
    ops.node(10020301, Axis3, Floor2 + 612.14/2)
    ops.node(10020401, Axis4, Floor2 + 612.14/2)

    ops.node(10030102, Axis1, Floor3 - 612.14/2)
    ops.node(10030202, Axis2, Floor3 - 612.14/2)
    ops.node(10030302, Axis3, Floor3 - 612.14/2)
    ops.node(10030402, Axis4, Floor3 - 612.14/2)

    ops.node(10030101, Axis1, Floor3 + 612.14/2)
    ops.node(10030201, Axis2, Floor3 + 612.14/2)
    ops.node(10030301, Axis3, Floor3 + 612.14/2)
    ops.node(10030401, Axis4, Floor3 + 612.14/2)

    ops.node(10040102, Axis1, Floor4 - 607.06/2)
    ops.node(10040202, Axis2, Floor4 - 607.06/2)
    ops.node(10040302, Axis3, Floor4 - 607.06/2)
    ops.node(10040402, Axis4, Floor4 - 607.06/2)

    ops.node(10040101, Axis1, Floor4 + 607.06/2)
    ops.node(10040201, Axis2, Floor4 + 607.06/2)
    ops.node(10040301, Axis3, Floor4 + 607.06/2)
    ops.node(10040401, Axis4, Floor4 + 607.06/2)

    ops.node(10050102, Axis1, Floor5 - 607.06/2)
    ops.node(10050202, Axis2, Floor5 - 607.06/2)
    ops.node(10050302, Axis3, Floor5 - 607.06/2)
    ops.node(10050402, Axis4, Floor5 - 607.06/2)

    ops.node(10050101, Axis1, Floor5 + 607.06/2)
    ops.node(10050201, Axis2, Floor5 + 607.06/2)
    ops.node(10050301, Axis3, Floor5 + 607.06/2)
    ops.node(10050401, Axis4, Floor5 + 607.06/2)

    ops.node(10060102, Axis1, Floor6 - 599.44/2)
    ops.node(10060202, Axis2, Floor6 - 599.44/2)
    ops.node(10060302, Axis3, Floor6 - 599.44/2)
    ops.node(10060402, Axis4, Floor6 - 599.44/2)

    ops.node(10060101, Axis1, Floor6 + 599.44/2)
    ops.node(10060201, Axis2, Floor6 + 599.44/2)
    ops.node(10060301, Axis3, Floor6 + 599.44/2)
    ops.node(10060401, Axis4, Floor6 + 599.44/2)

    ops.node(10070102, Axis1, Floor7 - 599.44/2)
    ops.node(10070202, Axis2, Floor7 - 599.44/2)
    ops.node(10070302, Axis3, Floor7 - 599.44/2)
    ops.node(10070402, Axis4, Floor7 - 599.44/2)

    ops.node(10070101, Axis1, Floor7 + 599.44/2)
    ops.node(10070201, Axis2, Floor7 + 599.44/2)
    ops.node(10070301, Axis3, Floor7 + 599.44/2)
    ops.node(10070401, Axis4, Floor7 + 599.44/2)

    ops.node(10080102, Axis1, Floor8 - 525.78/2)
    ops.node(10080202, Axis2, Floor8 - 525.78/2)
    ops.node(10080302, Axis3, Floor8 - 525.78/2)
    ops.node(10080402, Axis4, Floor8 - 525.78/2)

    ops.node(10080101, Axis1, Floor8 + 525.78/2)
    ops.node(10080201, Axis2, Floor8 + 525.78/2)
    ops.node(10080301, Axis3, Floor8 + 525.78/2)
    ops.node(10080401, Axis4, Floor8 + 525.78/2)

    ops.node(10090102, Axis1, Floor9 - 525.78/2)
    ops.node(10090202, Axis2, Floor9 - 525.78/2)
    ops.node(10090302, Axis3, Floor9 - 525.78/2)
    ops.node(10090402, Axis4, Floor9 - 525.78/2)

    
    # Moment frame beam nodes
    ops.node(10020104, Axis1 + 626.75, Floor2)
    ops.node(10020205, Axis2 - 631.83, Floor2)
    ops.node(10020204, Axis2 + 631.83, Floor2)
    ops.node(10020305, Axis3 - 631.83, Floor2)
    ops.node(10020304, Axis3 + 631.83, Floor2)
    ops.node(10020405, Axis4 - 626.75, Floor2)

    ops.node(10030104, Axis1 + 626.75, Floor3)
    ops.node(10030205, Axis2 - 631.83, Floor3)
    ops.node(10030204, Axis2 + 631.83, Floor3)
    ops.node(10030305, Axis3 - 631.83, Floor3)
    ops.node(10030304, Axis3 + 631.83, Floor3)
    ops.node(10030405, Axis4 - 626.75, Floor3)

    ops.node(10040104, Axis1 + 607.85, Floor4)
    ops.node(10040205, Axis2 - 629.44, Floor4)
    ops.node(10040204, Axis2 + 629.44, Floor4)
    ops.node(10040305, Axis3 - 629.44, Floor4)
    ops.node(10040304, Axis3 + 629.44, Floor4)
    ops.node(10040405, Axis4 - 607.85, Floor4)

    ops.node(10050104, Axis1 + 607.85, Floor5)
    ops.node(10050205, Axis2 - 629.44, Floor5)
    ops.node(10050204, Axis2 + 629.44, Floor5)
    ops.node(10050305, Axis3 - 629.44, Floor5)
    ops.node(10050304, Axis3 + 629.44, Floor5)
    ops.node(10050405, Axis4 - 607.85, Floor5)

    ops.node(10060104, Axis1 + 571.02, Floor6)
    ops.node(10060205, Axis2 - 583.72, Floor6)
    ops.node(10060204, Axis2 + 583.72, Floor6)
    ops.node(10060305, Axis3 - 583.72, Floor6)
    ops.node(10060304, Axis3 + 583.72, Floor6)
    ops.node(10060405, Axis4 - 571.02, Floor6)

    ops.node(10070104, Axis1 + 571.02, Floor7)
    ops.node(10070205, Axis2 - 583.72, Floor7)
    ops.node(10070204, Axis2 + 583.72, Floor7)
    ops.node(10070305, Axis3 - 583.72, Floor7)
    ops.node(10070304, Axis3 + 583.72, Floor7)
    ops.node(10070405, Axis4 - 571.02, Floor7)

    ops.node(10080104, Axis1 + 530.23, Floor8)
    ops.node(10080205, Axis2 - 541.65, Floor8)
    ops.node(10080204, Axis2 + 541.65, Floor8)
    ops.node(10080305, Axis3 - 541.65, Floor8)
    ops.node(10080304, Axis3 + 541.65, Floor8)
    ops.node(10080405, Axis4 - 530.23, Floor8)

    ops.node(10090104, Axis1 + 530.23, Floor9)
    ops.node(10090205, Axis2 - 541.65, Floor9)
    ops.node(10090204, Axis2 + 541.65, Floor9)
    ops.node(10090305, Axis3 - 541.65, Floor9)
    ops.node(10090304, Axis3 + 541.65, Floor9)
    ops.node(10090405, Axis4 - 530.23, Floor9)

    
    # Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)
    ops.node(10020103, Axis1 + 626.75, Floor2)
    ops.node(10020206, Axis2 - 631.83, Floor2)
    ops.node(10020203, Axis2 + 631.83, Floor2)
    ops.node(10020306, Axis3 - 631.83, Floor2)
    ops.node(10020303, Axis3 + 631.83, Floor2)
    ops.node(10020406, Axis4 - 626.75, Floor2)

    ops.node(10030103, Axis1 + 626.75, Floor3)
    ops.node(10030206, Axis2 - 631.83, Floor3)
    ops.node(10030203, Axis2 + 631.83, Floor3)
    ops.node(10030306, Axis3 - 631.83, Floor3)
    ops.node(10030303, Axis3 + 631.83, Floor3)
    ops.node(10030406, Axis4 - 626.75, Floor3)

    ops.node(10040103, Axis1 + 607.85, Floor4)
    ops.node(10040206, Axis2 - 629.44, Floor4)
    ops.node(10040203, Axis2 + 629.44, Floor4)
    ops.node(10040306, Axis3 - 629.44, Floor4)
    ops.node(10040303, Axis3 + 629.44, Floor4)
    ops.node(10040406, Axis4 - 607.85, Floor4)

    ops.node(10050103, Axis1 + 607.85, Floor5)
    ops.node(10050206, Axis2 - 629.44, Floor5)
    ops.node(10050203, Axis2 + 629.44, Floor5)
    ops.node(10050306, Axis3 - 629.44, Floor5)
    ops.node(10050303, Axis3 + 629.44, Floor5)
    ops.node(10050406, Axis4 - 607.85, Floor5)

    ops.node(10060103, Axis1 + 571.02, Floor6)
    ops.node(10060206, Axis2 - 583.72, Floor6)
    ops.node(10060203, Axis2 + 583.72, Floor6)
    ops.node(10060306, Axis3 - 583.72, Floor6)
    ops.node(10060303, Axis3 + 583.72, Floor6)
    ops.node(10060406, Axis4 - 571.02, Floor6)

    ops.node(10070103, Axis1 + 571.02, Floor7)
    ops.node(10070206, Axis2 - 583.72, Floor7)
    ops.node(10070203, Axis2 + 583.72, Floor7)
    ops.node(10070306, Axis3 - 583.72, Floor7)
    ops.node(10070303, Axis3 + 583.72, Floor7)
    ops.node(10070406, Axis4 - 571.02, Floor7)

    ops.node(10080103, Axis1 + 530.23, Floor8)
    ops.node(10080206, Axis2 - 541.65, Floor8)
    ops.node(10080203, Axis2 + 541.65, Floor8)
    ops.node(10080306, Axis3 - 541.65, Floor8)
    ops.node(10080303, Axis3 + 541.65, Floor8)
    ops.node(10080406, Axis4 - 530.23, Floor8)

    ops.node(10090103, Axis1 + 530.23, Floor9)
    ops.node(10090206, Axis2 - 541.65, Floor9)
    ops.node(10090203, Axis2 + 541.65, Floor9)
    ops.node(10090306, Axis3 - 541.65, Floor9)
    ops.node(10090303, Axis3 + 541.65, Floor9)
    ops.node(10090406, Axis4 - 530.23, Floor9)

    
    # Column splice ndoes
    ops.node(10030107, Axis1, Floor3 + 0.5 * 4300.00)
    ops.node(10030207, Axis2, Floor3 + 0.5 * 4300.00)
    ops.node(10030307, Axis3, Floor3 + 0.5 * 4300.00)
    ops.node(10030407, Axis4, Floor3 + 0.5 * 4300.00)

    ops.node(10050107, Axis1, Floor5 + 0.5 * 4300.00)
    ops.node(10050207, Axis2, Floor5 + 0.5 * 4300.00)
    ops.node(10050307, Axis3, Floor5 + 0.5 * 4300.00)
    ops.node(10050407, Axis4, Floor5 + 0.5 * 4300.00)

    ops.node(10070107, Axis1, Floor7 + 0.5 * 4300.00)
    ops.node(10070207, Axis2, Floor7 + 0.5 * 4300.00)
    ops.node(10070307, Axis3, Floor7 + 0.5 * 4300.00)
    ops.node(10070407, Axis4, Floor7 + 0.5 * 4300.00)

    
    # Beam splice ndoes
    ops.node(10020108, Axis1 + 9150.00 / 2, Floor2)
    ops.node(10020308, Axis3 + 9150.00 / 2, Floor2)

    ops.node(10030108, Axis1 + 9150.00 / 2, Floor3)
    ops.node(10030308, Axis3 + 9150.00 / 2, Floor3)

    ops.node(10040108, Axis1 + 9150.00 / 2, Floor4)
    ops.node(10040308, Axis3 + 9150.00 / 2, Floor4)

    ops.node(10050108, Axis1 + 9150.00 / 2, Floor5)
    ops.node(10050308, Axis3 + 9150.00 / 2, Floor5)

    ops.node(10060108, Axis1 + 9150.00 / 2, Floor6)
    ops.node(10060308, Axis3 + 9150.00 / 2, Floor6)

    ops.node(10070108, Axis1 + 9150.00 / 2, Floor7)
    ops.node(10070308, Axis3 + 9150.00 / 2, Floor7)

    ops.node(10080108, Axis1 + 9150.00 / 2, Floor8)
    ops.node(10080308, Axis3 + 9150.00 / 2, Floor8)

    ops.node(10090108, Axis1 + 9150.00 / 2, Floor9)
    ops.node(10090308, Axis3 + 9150.00 / 2, Floor9)

    
    
    # ----------------------------------- Elements -----------------------------------

    n = 10.

    # Column elements
    ops.element("elasticBeamColumn", 10010101, 10010101, 10020102, 33161.22, E, (n+1)/n*1435998418.32, 2)
    ops.element("elasticBeamColumn", 10010201, 10010201, 10020202, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10010301, 10010301, 10020302, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10010401, 10010401, 10020402, 33161.22, E, (n+1)/n*1435998418.32, 2)

    ops.element("elasticBeamColumn", 10020101, 10020101, 10030102, 33161.22, E, (n+1)/n*1435998418.32, 2)
    ops.element("elasticBeamColumn", 10020201, 10020201, 10030202, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10020301, 10020301, 10030302, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10020401, 10020401, 10030402, 33161.22, E, (n+1)/n*1435998418.32, 2)

    ops.element("elasticBeamColumn", 10030102, 10030101, 10030107, 20064.48, E, (n+1)/n*795002022.90, 2)
    ops.element("elasticBeamColumn", 10030202, 10030201, 10030207, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10030302, 10030301, 10030307, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10030402, 10030401, 10030407, 20064.48, E, (n+1)/n*795002022.90, 2)

    ops.element("elasticBeamColumn", 10030103, 10030107, 10040102, 20064.48, E, (n+1)/n*795002022.90, 2)
    ops.element("elasticBeamColumn", 10030203, 10030207, 10040202, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10030303, 10030307, 10040302, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10030403, 10030407, 10040402, 20064.48, E, (n+1)/n*795002022.90, 2)

    ops.element("elasticBeamColumn", 10040101, 10040101, 10050102, 20064.48, E, (n+1)/n*795002022.90, 2)
    ops.element("elasticBeamColumn", 10040201, 10040201, 10050202, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10040301, 10040301, 10050302, 36257.99, E, (n+1)/n*1610815617.07, 2)
    ops.element("elasticBeamColumn", 10040401, 10040401, 10050402, 20064.48, E, (n+1)/n*795002022.90, 2)

    ops.element("elasticBeamColumn", 10050102, 10050101, 10050107, 13483.84, E, (n+1)/n*486990767.95, 2)
    ops.element("elasticBeamColumn", 10050202, 10050201, 10050207, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10050302, 10050301, 10050307, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10050402, 10050401, 10050407, 13483.84, E, (n+1)/n*486990767.95, 2)

    ops.element("elasticBeamColumn", 10050103, 10050107, 10060102, 13483.84, E, (n+1)/n*486990767.95, 2)
    ops.element("elasticBeamColumn", 10050203, 10050207, 10060202, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10050303, 10050307, 10060302, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10050403, 10050407, 10060402, 13483.84, E, (n+1)/n*486990767.95, 2)

    ops.element("elasticBeamColumn", 10060101, 10060101, 10070102, 13483.84, E, (n+1)/n*486990767.95, 2)
    ops.element("elasticBeamColumn", 10060201, 10060201, 10070202, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10060301, 10060301, 10070302, 27096.72, E, (n+1)/n*1144636420.40, 2)
    ops.element("elasticBeamColumn", 10060401, 10060401, 10070402, 13483.84, E, (n+1)/n*486990767.95, 2)

    ops.element("elasticBeamColumn", 10070102, 10070101, 10070107, 10451.59, E, (n+1)/n*370445968.78, 2)
    ops.element("elasticBeamColumn", 10070202, 10070201, 10070207, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10070302, 10070301, 10070307, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10070402, 10070401, 10070407, 10451.59, E, (n+1)/n*370445968.78, 2)

    ops.element("elasticBeamColumn", 10070103, 10070107, 10080102, 10451.59, E, (n+1)/n*370445968.78, 2)
    ops.element("elasticBeamColumn", 10070203, 10070207, 10080202, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10070303, 10070307, 10080302, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10070403, 10070407, 10080402, 10451.59, E, (n+1)/n*370445968.78, 2)

    ops.element("elasticBeamColumn", 10080101, 10080101, 10090102, 10451.59, E, (n+1)/n*370445968.78, 2)
    ops.element("elasticBeamColumn", 10080201, 10080201, 10090202, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10080301, 10080301, 10090302, 22645.12, E, (n+1)/n*911546822.06, 2)
    ops.element("elasticBeamColumn", 10080401, 10080401, 10090402, 10451.59, E, (n+1)/n*370445968.78, 2)

    
    # Beam elements
    ops.element("elasticBeamColumn", 10020111, 10020104, 10020108, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10020112, 10020108, 10020205, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10020204, 10020204, 10020305, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10020311, 10020304, 10020308, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10020312, 10020308, 10020405, 15935.45, E, (n+1)/n*986468478.67, 2)

    ops.element("elasticBeamColumn", 10030111, 10030104, 10030108, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10030112, 10030108, 10030205, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10030204, 10030204, 10030305, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10030311, 10030304, 10030308, 15935.45, E, (n+1)/n*986468478.67, 2)
    ops.element("elasticBeamColumn", 10030312, 10030308, 10030405, 15935.45, E, (n+1)/n*986468478.67, 2)

    ops.element("elasticBeamColumn", 10040111, 10040104, 10040108, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040112, 10040108, 10040205, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040204, 10040204, 10040305, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040311, 10040304, 10040308, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040312, 10040308, 10040405, 14451.58, E, (n+1)/n*874085993.76, 2)

    ops.element("elasticBeamColumn", 10050111, 10050104, 10050108, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10050112, 10050108, 10050205, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10050204, 10050204, 10050305, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10050311, 10050304, 10050308, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10050312, 10050308, 10050405, 14451.58, E, (n+1)/n*874085993.76, 2)

    ops.element("elasticBeamColumn", 10060111, 10060104, 10060108, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10060112, 10060108, 10060205, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10060204, 10060204, 10060305, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10060311, 10060304, 10060308, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10060312, 10060308, 10060405, 10451.59, E, (n+1)/n*561912424.56, 2)

    ops.element("elasticBeamColumn", 10070111, 10070104, 10070108, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10070112, 10070108, 10070205, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10070204, 10070204, 10070305, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10070311, 10070304, 10070308, 10451.59, E, (n+1)/n*561912424.56, 2)
    ops.element("elasticBeamColumn", 10070312, 10070308, 10070405, 10451.59, E, (n+1)/n*561912424.56, 2)

    ops.element("elasticBeamColumn", 10080111, 10080104, 10080108, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10080112, 10080108, 10080205, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10080204, 10080204, 10080305, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10080311, 10080304, 10080308, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10080312, 10080308, 10080405, 8387.08, E, (n+1)/n*350883091.78, 2)

    ops.element("elasticBeamColumn", 10090111, 10090104, 10090108, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10090112, 10090108, 10090205, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10090204, 10090204, 10090305, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10090311, 10090304, 10090308, 8387.08, E, (n+1)/n*350883091.78, 2)
    ops.element("elasticBeamColumn", 10090312, 10090308, 10090405, 8387.08, E, (n+1)/n*350883091.78, 2)


    # Panel zones
    # PanelNone(Floor, Axis, X, Y, E, mu, fy_column, A_stiff, I_stiff, d_col, d_beam, tp, tf, bf, transfTag, type_, position, check=None)
    PanelZone(2, 1, Axis1, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 508.00, 612.14, 22.61, 40.39, 289.56, 2, 1, "L")
    PanelZone(2, 2, Axis2, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 612.14, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(2, 3, Axis3, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 612.14, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(2, 4, Axis4, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 508.00, 612.14, 22.61, 40.39, 289.56, 2, 1, "R")

    PanelZone(3, 1, Axis1, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 508.00, 612.14, 22.61, 40.39, 289.56, 2, 1, "L")
    PanelZone(3, 2, Axis2, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 612.14, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(3, 3, Axis3, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 612.14, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(3, 4, Axis4, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 508.00, 612.14, 22.61, 40.39, 289.56, 2, 1, "R")

    PanelZone(4, 1, Axis1, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 474.98, 607.06, 14.99, 23.88, 284.48, 2, 1, "L")
    PanelZone(4, 2, Axis2, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 607.06, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(4, 3, Axis3, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 607.06, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(4, 4, Axis4, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 474.98, 607.06, 14.99, 23.88, 284.48, 2, 1, "R")

    PanelZone(5, 1, Axis1, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 474.98, 607.06, 14.99, 23.88, 284.48, 2, 1, "L")
    PanelZone(5, 2, Axis2, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 607.06, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(5, 3, Axis3, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 518.16, 607.06, 24.38, 44.45, 292.10, 2, 1, "I")
    PanelZone(5, 4, Axis4, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 474.98, 607.06, 14.99, 23.88, 284.48, 2, 1, "R")

    PanelZone(6, 1, Axis1, Floor6, E, mu, fy_column, A_Stiff, I_Stiff, 469.90, 599.44, 12.57, 20.57, 194.06, 2, 1, "L")
    PanelZone(6, 2, Axis2, Floor6, E, mu, fy_column, A_Stiff, I_Stiff, 495.30, 599.44, 18.54, 33.53, 284.48, 2, 1, "I")
    PanelZone(6, 3, Axis3, Floor6, E, mu, fy_column, A_Stiff, I_Stiff, 495.30, 599.44, 18.54, 33.53, 284.48, 2, 1, "I")
    PanelZone(6, 4, Axis4, Floor6, E, mu, fy_column, A_Stiff, I_Stiff, 469.90, 599.44, 12.57, 20.57, 194.06, 2, 1, "R")

    PanelZone(7, 1, Axis1, Floor7, E, mu, fy_column, A_Stiff, I_Stiff, 469.90, 599.44, 12.57, 20.57, 194.06, 2, 1, "L")
    PanelZone(7, 2, Axis2, Floor7, E, mu, fy_column, A_Stiff, I_Stiff, 495.30, 599.44, 18.54, 33.53, 284.48, 2, 1, "I")
    PanelZone(7, 3, Axis3, Floor7, E, mu, fy_column, A_Stiff, I_Stiff, 495.30, 599.44, 18.54, 33.53, 284.48, 2, 1, "I")
    PanelZone(7, 4, Axis4, Floor7, E, mu, fy_column, A_Stiff, I_Stiff, 469.90, 599.44, 12.57, 20.57, 194.06, 2, 1, "R")

    PanelZone(8, 1, Axis1, Floor8, E, mu, fy_column, A_Stiff, I_Stiff, 459.74, 525.78, 9.91, 16.00, 191.26, 2, 1, "L")
    PanelZone(8, 2, Axis2, Floor8, E, mu, fy_column, A_Stiff, I_Stiff, 482.60, 525.78, 16.64, 26.92, 287.02, 2, 1, "I")
    PanelZone(8, 3, Axis3, Floor8, E, mu, fy_column, A_Stiff, I_Stiff, 482.60, 525.78, 16.64, 26.92, 287.02, 2, 1, "I")
    PanelZone(8, 4, Axis4, Floor8, E, mu, fy_column, A_Stiff, I_Stiff, 459.74, 525.78, 9.91, 16.00, 191.26, 2, 1, "R")

    PanelZone(9, 1, Axis1, Floor9, E, mu, fy_column, A_Stiff, I_Stiff, 459.74, 525.78, 9.91, 16.00, 191.26, 2, 1, "LT")
    PanelZone(9, 2, Axis2, Floor9, E, mu, fy_column, A_Stiff, I_Stiff, 482.60, 525.78, 16.64, 26.92, 287.02, 2, 1, "T")
    PanelZone(9, 3, Axis3, Floor9, E, mu, fy_column, A_Stiff, I_Stiff, 482.60, 525.78, 16.64, 26.92, 287.02, 2, 1, "T")
    PanelZone(9, 4, Axis4, Floor9, E, mu, fy_column, A_Stiff, I_Stiff, 459.74, 525.78, 9.91, 16.00, 191.26, 2, 1, "RT")


    # RBS elements (If RBS length equal zero, RBS element will not be generated)
    ops.element("elasticBeamColumn", 10020105, 11020104, 10020103, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10020106, 10020206, 11020202, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10020205, 11020204, 10020203, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10020206, 10020306, 11020302, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10020305, 11020304, 10020303, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10020306, 10020406, 11020402, 15935.45, E, 986468478.67, 2)

    ops.element("elasticBeamColumn", 10030105, 11030104, 10030103, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10030106, 10030206, 11030202, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10030205, 11030204, 10030203, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10030206, 10030306, 11030302, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10030305, 11030304, 10030303, 15935.45, E, 986468478.67, 2)
    ops.element("elasticBeamColumn", 10030306, 10030406, 11030402, 15935.45, E, 986468478.67, 2)

    ops.element("elasticBeamColumn", 10040105, 11040104, 10040103, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10040106, 10040206, 11040202, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10040205, 11040204, 10040203, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10040206, 10040306, 11040302, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10040305, 11040304, 10040303, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10040306, 10040406, 11040402, 14451.58, E, 874085993.76, 2)

    ops.element("elasticBeamColumn", 10050105, 11050104, 10050103, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10050106, 10050206, 11050202, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10050205, 11050204, 10050203, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10050206, 10050306, 11050302, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10050305, 11050304, 10050303, 14451.58, E, 874085993.76, 2)
    ops.element("elasticBeamColumn", 10050306, 10050406, 11050402, 14451.58, E, 874085993.76, 2)

    ops.element("elasticBeamColumn", 10060105, 11060104, 10060103, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10060106, 10060206, 11060202, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10060205, 11060204, 10060203, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10060206, 10060306, 11060302, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10060305, 11060304, 10060303, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10060306, 10060406, 11060402, 10451.59, E, 561912424.56, 2)

    ops.element("elasticBeamColumn", 10070105, 11070104, 10070103, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10070106, 10070206, 11070202, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10070205, 11070204, 10070203, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10070206, 10070306, 11070302, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10070305, 11070304, 10070303, 10451.59, E, 561912424.56, 2)
    ops.element("elasticBeamColumn", 10070306, 10070406, 11070402, 10451.59, E, 561912424.56, 2)

    ops.element("elasticBeamColumn", 10080105, 11080104, 10080103, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10080106, 10080206, 11080202, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10080205, 11080204, 10080203, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10080206, 10080306, 11080302, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10080305, 11080304, 10080303, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10080306, 10080406, 11080402, 8387.08, E, 350883091.78, 2)

    ops.element("elasticBeamColumn", 10090105, 11090104, 10090103, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10090106, 10090206, 11090202, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10090205, 11090204, 10090203, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10090206, 10090306, 11090302, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10090305, 11090304, 10090303, 8387.08, E, 350883091.78, 2)
    ops.element("elasticBeamColumn", 10090306, 10090406, 11090402, 8387.08, E, 350883091.78, 2)


    
    # Beam hinges
    # BeamHinge(SpringID, NodeI, NodeJ, E, fy_beam, Ix, d, htw, bftf, ry, L, Ls, Lb, My, type_, check=None)
    BeamHinge(10020109, 10020103, 10020104, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10020210, 10020205, 10020206, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10020209, 10020203, 10020204, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8631.8, 4315.9, 4315.9, 1266392305.92, 1)
    BeamHinge(10020310, 10020305, 10020306, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8631.8, 4315.9, 4315.9, 1266392305.92, 1)
    BeamHinge(10020309, 10020303, 10020304, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10020410, 10020405, 10020406, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)

    BeamHinge(10030109, 10030103, 10030104, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10030210, 10030205, 10030206, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10030209, 10030203, 10030204, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8631.8, 4315.9, 4315.9, 1266392305.92, 1)
    BeamHinge(10030310, 10030305, 10030306, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8631.8, 4315.9, 4315.9, 1266392305.92, 1)
    BeamHinge(10030309, 10030303, 10030304, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)
    BeamHinge(10030410, 10030405, 10030406, E, fy_beam, 986468478.67, 612.14, 45.87, 5.86, 49.66, 8636.9, 4318.5, 4318.5, 1266392305.92, 3)

    BeamHinge(10040109, 10040103, 10040104, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10040210, 10040205, 10040206, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10040209, 10040203, 10040204, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8631.8, 4315.9, 4315.9, 1130707416.00, 1)
    BeamHinge(10040310, 10040305, 10040306, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8631.8, 4315.9, 4315.9, 1130707416.00, 1)
    BeamHinge(10040309, 10040303, 10040304, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10040410, 10040405, 10040406, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)

    BeamHinge(10050109, 10050103, 10050104, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10050210, 10050205, 10050206, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10050209, 10050203, 10050204, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8631.8, 4315.9, 4315.9, 1130707416.00, 1)
    BeamHinge(10050310, 10050305, 10050306, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8631.8, 4315.9, 4315.9, 1130707416.00, 1)
    BeamHinge(10050309, 10050303, 10050304, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)
    BeamHinge(10050410, 10050405, 10050406, E, fy_beam, 874085993.76, 607.06, 48.95, 6.61, 48.75, 8653.4, 4326.7, 4326.7, 1130707416.00, 3)

    BeamHinge(10060109, 10060103, 10060104, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10060210, 10060205, 10060206, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10060209, 10060203, 10060204, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8654.7, 4327.4, 4327.4, 757573968.72, 1)
    BeamHinge(10060310, 10060305, 10060306, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8654.7, 4327.4, 4327.4, 757573968.72, 1)
    BeamHinge(10060309, 10060303, 10060304, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10060410, 10060405, 10060406, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)

    BeamHinge(10070109, 10070103, 10070104, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10070210, 10070205, 10070206, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10070209, 10070203, 10070204, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8654.7, 4327.4, 4327.4, 757573968.72, 1)
    BeamHinge(10070310, 10070305, 10070306, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8654.7, 4327.4, 4327.4, 757573968.72, 1)
    BeamHinge(10070309, 10070303, 10070304, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)
    BeamHinge(10070410, 10070405, 10070406, E, fy_beam, 561912424.56, 599.44, 54.63, 6.94, 34.04, 8667.4, 4333.7, 4333.7, 757573968.72, 3)

    BeamHinge(10080109, 10080103, 10080104, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10080210, 10080205, 10080206, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10080209, 10080203, 10080204, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8667.4, 4333.7, 4333.7, 539347437.43, 1)
    BeamHinge(10080310, 10080305, 10080306, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8667.4, 4333.7, 4333.7, 539347437.43, 1)
    BeamHinge(10080309, 10080303, 10080304, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10080410, 10080405, 10080406, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)

    BeamHinge(10090109, 10090103, 10090104, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10090210, 10090205, 10090206, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10090209, 10090203, 10090204, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8667.4, 4333.7, 4333.7, 539347437.43, 1)
    BeamHinge(10090310, 10090305, 10090306, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8667.4, 4333.7, 4333.7, 539347437.43, 1)
    BeamHinge(10090309, 10090303, 10090304, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)
    BeamHinge(10090410, 10090405, 10090406, E, fy_beam, 350883091.78, 525.78, 53.71, 7.22, 32.05, 8678.8, 4339.4, 4339.4, 539347437.43, 3)

    # Column hinges
    # Column(SpringID, NodeI, NodeJ, E, Ix, d, htw, ry, L, Lb, My, PPy, SF_PPy, pinned, check=None)
    ColumnHinge(10010107, 10010100, 10010101, E, 1435998418.32, 508.00, 18.00, 70.06, 5193.93, 5193.93, 2250107757.84, 0.0000, 1.25, 1)
    ColumnHinge(10010207, 10010200, 10010201, E, 1610815617.07, 518.16, 16.77, 71.07, 5193.93, 5193.93, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10010307, 10010300, 10010301, E, 1610815617.07, 518.16, 16.77, 71.07, 5193.93, 5193.93, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10010407, 10010400, 10010401, E, 1435998418.32, 508.00, 18.00, 70.06, 5193.93, 5193.93, 2250107757.84, 0.0000, 1.25, 1)

    ColumnHinge(10020108, 10020102, 11020101, E, 1435998418.32, 508.00, 18.00, 70.06, 5193.93, 5193.93, 2250107757.84, 0.0000, 1.25, 1)
    ColumnHinge(10020208, 10020202, 11020201, E, 1610815617.07, 518.16, 16.77, 71.07, 5193.93, 5193.93, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10020308, 10020302, 11020301, E, 1610815617.07, 518.16, 16.77, 71.07, 5193.93, 5193.93, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10020408, 10020402, 11020401, E, 1435998418.32, 508.00, 18.00, 70.06, 5193.93, 5193.93, 2250107757.84, 0.0000, 1.25, 1)

    ColumnHinge(10020107, 11020103, 10020101, E, 1435998418.32, 508.00, 18.00, 70.06, 3687.86, 3687.86, 2250107757.84, 0.0000, 1.25, 1)
    ColumnHinge(10020207, 11020203, 10020201, E, 1610815617.07, 518.16, 16.77, 71.07, 3687.86, 3687.86, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10020307, 11020303, 10020301, E, 1610815617.07, 518.16, 16.77, 71.07, 3687.86, 3687.86, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10020407, 11020403, 10020401, E, 1435998418.32, 508.00, 18.00, 70.06, 3687.86, 3687.86, 2250107757.84, 0.0000, 1.25, 1)

    ColumnHinge(10030108, 10030102, 11030101, E, 1435998418.32, 508.00, 18.00, 70.06, 3687.86, 3687.86, 2250107757.84, 0.0000, 1.25, 1)
    ColumnHinge(10030208, 10030202, 11030201, E, 1610815617.07, 518.16, 16.77, 71.07, 3687.86, 3687.86, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10030308, 10030302, 11030301, E, 1610815617.07, 518.16, 16.77, 71.07, 3687.86, 3687.86, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10030408, 10030402, 11030401, E, 1435998418.32, 508.00, 18.00, 70.06, 3687.86, 3687.86, 2250107757.84, 0.0000, 1.25, 1)

    ColumnHinge(10030107, 11030103, 10030101, E, 795002022.90, 474.98, 27.15, 67.56, 3690.40, 3690.40, 1300313528.40, 0.0000, 1.25, 1)
    ColumnHinge(10030207, 11030203, 10030201, E, 1610815617.07, 518.16, 16.77, 71.07, 3690.40, 3690.40, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10030307, 11030303, 10030301, E, 1610815617.07, 518.16, 16.77, 71.07, 3690.40, 3690.40, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10030407, 11030403, 10030401, E, 795002022.90, 474.98, 27.15, 67.56, 3690.40, 3690.40, 1300313528.40, 0.0000, 1.25, 1)

    ColumnHinge(10040108, 10040102, 11040101, E, 795002022.90, 474.98, 27.15, 67.56, 3690.40, 3690.40, 1300313528.40, 0.0000, 1.25, 1)
    ColumnHinge(10040208, 10040202, 11040201, E, 1610815617.07, 518.16, 16.77, 71.07, 3690.40, 3690.40, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10040308, 10040302, 11040301, E, 1610815617.07, 518.16, 16.77, 71.07, 3690.40, 3690.40, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10040408, 10040402, 11040401, E, 795002022.90, 474.98, 27.15, 67.56, 3690.40, 3690.40, 1300313528.40, 0.0000, 1.25, 1)

    ColumnHinge(10040107, 11040103, 10040101, E, 795002022.90, 474.98, 27.15, 67.56, 3692.94, 3692.94, 1300313528.40, 0.0000, 1.25, 1)
    ColumnHinge(10040207, 11040203, 10040201, E, 1610815617.07, 518.16, 16.77, 71.07, 3692.94, 3692.94, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10040307, 11040303, 10040301, E, 1610815617.07, 518.16, 16.77, 71.07, 3692.94, 3692.94, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10040407, 11040403, 10040401, E, 795002022.90, 474.98, 27.15, 67.56, 3692.94, 3692.94, 1300313528.40, 0.0000, 1.25, 1)

    ColumnHinge(10050108, 10050102, 11050101, E, 795002022.90, 474.98, 27.15, 67.56, 3692.94, 3692.94, 1300313528.40, 0.0000, 1.25, 1)
    ColumnHinge(10050208, 10050202, 11050201, E, 1610815617.07, 518.16, 16.77, 71.07, 3692.94, 3692.94, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10050308, 10050302, 11050301, E, 1610815617.07, 518.16, 16.77, 71.07, 3692.94, 3692.94, 2498863389.36, 0.0000, 1.25, 1)
    ColumnHinge(10050408, 10050402, 11050401, E, 795002022.90, 474.98, 27.15, 67.56, 3692.94, 3692.94, 1300313528.40, 0.0000, 1.25, 1)

    ColumnHinge(10050107, 11050103, 10050101, E, 486990767.95, 469.90, 32.48, 43.14, 3696.75, 3696.75, 825416413.68, 0.0000, 1.25, 1)
    ColumnHinge(10050207, 11050203, 10050201, E, 1144636420.40, 495.30, 22.00, 69.12, 3696.75, 3696.75, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10050307, 11050303, 10050301, E, 1144636420.40, 495.30, 22.00, 69.12, 3696.75, 3696.75, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10050407, 11050403, 10050401, E, 486990767.95, 469.90, 32.48, 43.14, 3696.75, 3696.75, 825416413.68, 0.0000, 1.25, 1)

    ColumnHinge(10060108, 10060102, 11060101, E, 486990767.95, 469.90, 32.48, 43.14, 3696.75, 3696.75, 825416413.68, 0.0000, 1.25, 1)
    ColumnHinge(10060208, 10060202, 11060201, E, 1144636420.40, 495.30, 22.00, 69.12, 3696.75, 3696.75, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10060308, 10060302, 11060301, E, 1144636420.40, 495.30, 22.00, 69.12, 3696.75, 3696.75, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10060408, 10060402, 11060401, E, 486990767.95, 469.90, 32.48, 43.14, 3696.75, 3696.75, 825416413.68, 0.0000, 1.25, 1)

    ColumnHinge(10060107, 11060103, 10060101, E, 486990767.95, 469.90, 32.48, 43.14, 3700.56, 3700.56, 825416413.68, 0.0000, 1.25, 1)
    ColumnHinge(10060207, 11060203, 10060201, E, 1144636420.40, 495.30, 22.00, 69.12, 3700.56, 3700.56, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10060307, 11060303, 10060301, E, 1144636420.40, 495.30, 22.00, 69.12, 3700.56, 3700.56, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10060407, 11060403, 10060401, E, 486990767.95, 469.90, 32.48, 43.14, 3700.56, 3700.56, 825416413.68, 0.0000, 1.25, 1)

    ColumnHinge(10070108, 10070102, 11070101, E, 486990767.95, 469.90, 32.48, 43.14, 3700.56, 3700.56, 825416413.68, 0.0000, 1.25, 1)
    ColumnHinge(10070208, 10070202, 11070201, E, 1144636420.40, 495.30, 22.00, 69.12, 3700.56, 3700.56, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10070308, 10070302, 11070301, E, 1144636420.40, 495.30, 22.00, 69.12, 3700.56, 3700.56, 1820438939.76, 0.0000, 1.25, 1)
    ColumnHinge(10070408, 10070402, 11070401, E, 486990767.95, 469.90, 32.48, 43.14, 3700.56, 3700.56, 825416413.68, 0.0000, 1.25, 1)

    ColumnHinge(10070107, 11070103, 10070101, E, 370445968.78, 459.74, 41.13, 42.29, 3737.39, 3737.39, 633196152.96, 0.0000, 1.25, 1)
    ColumnHinge(10070207, 11070203, 10070201, E, 911546822.06, 482.60, 24.55, 68.19, 3737.39, 3737.39, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10070307, 11070303, 10070301, E, 911546822.06, 482.60, 24.55, 68.19, 3737.39, 3737.39, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10070407, 11070403, 10070401, E, 370445968.78, 459.74, 41.13, 42.29, 3737.39, 3737.39, 633196152.96, 0.0000, 1.25, 1)

    ColumnHinge(10080108, 10080102, 11080101, E, 370445968.78, 459.74, 41.13, 42.29, 3737.39, 3737.39, 633196152.96, 0.0000, 1.25, 1)
    ColumnHinge(10080208, 10080202, 11080201, E, 911546822.06, 482.60, 24.55, 68.19, 3737.39, 3737.39, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10080308, 10080302, 11080301, E, 911546822.06, 482.60, 24.55, 68.19, 3737.39, 3737.39, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10080408, 10080402, 11080401, E, 370445968.78, 459.74, 41.13, 42.29, 3737.39, 3737.39, 633196152.96, 0.0000, 1.25, 1)

    ColumnHinge(10080107, 11080103, 10080101, E, 370445968.78, 459.74, 41.13, 42.29, 3774.22, 3774.22, 633196152.96, 0.0000, 1.25, 1)
    ColumnHinge(10080207, 11080203, 10080201, E, 911546822.06, 482.60, 24.55, 68.19, 3774.22, 3774.22, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10080307, 11080303, 10080301, E, 911546822.06, 482.60, 24.55, 68.19, 3774.22, 3774.22, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10080407, 11080403, 10080401, E, 370445968.78, 459.74, 41.13, 42.29, 3774.22, 3774.22, 633196152.96, 0.0000, 1.25, 1)

    ColumnHinge(10090108, 10090102, 11090101, E, 370445968.78, 459.74, 41.13, 42.29, 3774.22, 3774.22, 633196152.96, 0.0000, 1.25, 1)
    ColumnHinge(10090208, 10090202, 11090201, E, 911546822.06, 482.60, 24.55, 68.19, 3774.22, 3774.22, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10090308, 10090302, 11090301, E, 911546822.06, 482.60, 24.55, 68.19, 3774.22, 3774.22, 1481226714.96, 0.0000, 1.25, 1)
    ColumnHinge(10090408, 10090402, 11090401, E, 370445968.78, 459.74, 41.13, 42.29, 3774.22, 3774.22, 633196152.96, 0.0000, 1.25, 1)


    T = 20
    define_smadb_brace_pairs(T)


    # Rigid links
    ops.element("truss", 10020404, 11020404, 10020500, A_Stiff, 99)
    ops.element("truss", 10030404, 11030404, 10030500, A_Stiff, 99)
    ops.element("truss", 10040404, 11040404, 10040500, A_Stiff, 99)
    ops.element("truss", 10050404, 11050404, 10050500, A_Stiff, 99)
    ops.element("truss", 10060404, 11060404, 10060500, A_Stiff, 99)
    ops.element("truss", 10070404, 11070404, 10070500, A_Stiff, 99)
    ops.element("truss", 10080404, 11080404, 10080500, A_Stiff, 99)
    ops.element("truss", 10090404, 11090404, 10090500, A_Stiff, 99)

    # Leaning column
    ops.element("elasticBeamColumn", 10010501, 10010500, 10020502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10020501, 10020501, 10030502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10030501, 10030501, 10040502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10040501, 10040501, 10050502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10050501, 10050501, 10060502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10060501, 10060501, 10070502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10070501, 10070501, 10080502, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10080501, 10080501, 10090502, A_Stiff, E, I_Stiff, 2)

    # Leaning column hinges
    Spring_Rigid(10020508, 10020502, 10020500)
    Spring_Zero(10020507, 10020500, 10020501)
    Spring_Rigid(10030508, 10030502, 10030500)
    Spring_Zero(10030507, 10030500, 10030501)
    Spring_Rigid(10040508, 10040502, 10040500)
    Spring_Zero(10040507, 10040500, 10040501)
    Spring_Rigid(10050508, 10050502, 10050500)
    Spring_Zero(10050507, 10050500, 10050501)
    Spring_Rigid(10060508, 10060502, 10060500)
    Spring_Zero(10060507, 10060500, 10060501)
    Spring_Rigid(10070508, 10070502, 10070500)
    Spring_Zero(10070507, 10070500, 10070501)
    Spring_Rigid(10080508, 10080502, 10080500)
    Spring_Zero(10080507, 10080500, 10080501)
    Spring_Rigid(10090508, 10090502, 10090500)

    # --------------------------------- Constraints ----------------------------------

    # Support
    ops.fix(10010100, 1, 1, 1)
    ops.fix(10010200, 1, 1, 1)
    ops.fix(10010300, 1, 1, 1)
    ops.fix(10010400, 1, 1, 1)
    ops.fix(10010500, 1, 1, 0)

    # Soil constraint
    # (No soil constraint)

    # Rigid diaphragm
    ops.equalDOF(11020204, 11020104, 1)
    ops.equalDOF(11020204, 11020304, 1)
    ops.equalDOF(11020204, 11020404, 1)

    ops.equalDOF(11030204, 11030104, 1)
    ops.equalDOF(11030204, 11030304, 1)
    ops.equalDOF(11030204, 11030404, 1)

    ops.equalDOF(11040204, 11040104, 1)
    ops.equalDOF(11040204, 11040304, 1)
    ops.equalDOF(11040204, 11040404, 1)

    ops.equalDOF(11050204, 11050104, 1)
    ops.equalDOF(11050204, 11050304, 1)
    ops.equalDOF(11050204, 11050404, 1)

    ops.equalDOF(11060204, 11060104, 1)
    ops.equalDOF(11060204, 11060304, 1)
    ops.equalDOF(11060204, 11060404, 1)

    ops.equalDOF(11070204, 11070104, 1)
    ops.equalDOF(11070204, 11070304, 1)
    ops.equalDOF(11070204, 11070404, 1)

    ops.equalDOF(11080204, 11080104, 1)
    ops.equalDOF(11080204, 11080304, 1)
    ops.equalDOF(11080204, 11080404, 1)

    ops.equalDOF(11090204, 11090104, 1)
    ops.equalDOF(11090204, 11090304, 1)
    ops.equalDOF(11090204, 11090404, 1)


    # ---------------------------------- Recorders -----------------------------------

    # Time
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Time.out"), "-time", "-node", 10010100, "-dof", 1, "disp")

    # Support reactions
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support1.out"), "-node", 10010100, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support2.out"), "-node", 10010200, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support3.out"), "-node", 10010300, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support4.out"), "-node", 10010400, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support5.out"), "-node", 10010500, "-dof", 1, 2, 3, "reaction")

    # Story drift ratio
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR1.out"), "-iNode", 10010100, "-jNode", 11020204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR2.out"), "-iNode", 11020204, "-jNode", 11030204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR3.out"), "-iNode", 11030204, "-jNode", 11040204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR4.out"), "-iNode", 11040204, "-jNode", 11050204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR5.out"), "-iNode", 11050204, "-jNode", 11060204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR6.out"), "-iNode", 11060204, "-jNode", 11070204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR7.out"), "-iNode", 11070204, "-jNode", 11080204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR8.out"), "-iNode", 11080204, "-jNode", 11090204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR_Roof.out"), "-iNode", 10010100, "-jNode", 11090204, "-dof", 1, "-perpDirn", 2)

    # Floor acceleration
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA1.out"), "-node", 10010100, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA2.out"), "-node", 11020204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA3.out"), "-node", 11030204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA4.out"), "-node", 11040204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA5.out"), "-node", 11050204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA6.out"), "-node", 11060204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA7.out"), "-node", 11070204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA8.out"), "-node", 11080204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA9.out"), "-node", 11090204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV1.out"), "-node", 10010100, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV2.out"), "-node", 11020204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV3.out"), "-node", 11030204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV4.out"), "-node", 11040204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV5.out"), "-node", 11050204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV6.out"), "-node", 11060204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV7.out"), "-node", 11070204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV8.out"), "-node", 11080204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV9.out"), "-node", 11090204, "-dof", 1, "vel")

    # Floor displacement
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp1.out"), "-node", 10010100, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp2.out"), "-node", 11020204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp3.out"), "-node", 11030204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp4.out"), "-node", 11040204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp5.out"), "-node", 11050204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp6.out"), "-node", 11060204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp7.out"), "-node", 11070204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp8.out"), "-node", 11080204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp9.out"), "-node", 11090204, "-dof", 1, "disp")

    # Shear forces
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_1.out"), "-ele", 10010101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_2.out"), "-ele", 10010201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_3.out"), "-ele", 10010301, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_4.out"), "-ele", 10010401, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_1.out"), "-ele", 10020101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_2.out"), "-ele", 10020201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_3.out"), "-ele", 10020301, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_4.out"), "-ele", 10020401, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_1.out"), "-ele", 10030102, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_2.out"), "-ele", 10030202, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_3.out"), "-ele", 10030302, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_4.out"), "-ele", 10030402, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_1.out"), "-ele", 10040101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_2.out"), "-ele", 10040201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_3.out"), "-ele", 10040301, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_4.out"), "-ele", 10040401, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear5_1.out"), "-ele", 10050102, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear5_2.out"), "-ele", 10050202, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear5_3.out"), "-ele", 10050302, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear5_4.out"), "-ele", 10050402, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear6_1.out"), "-ele", 10060101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear6_2.out"), "-ele", 10060201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear6_3.out"), "-ele", 10060301, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear6_4.out"), "-ele", 10060401, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear7_1.out"), "-ele", 10070102, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear7_2.out"), "-ele", 10070202, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear7_3.out"), "-ele", 10070302, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear7_4.out"), "-ele", 10070402, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear8_1.out"), "-ele", 10080101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear8_2.out"), "-ele", 10080201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear8_3.out"), "-ele", 10080301, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear8_4.out"), "-ele", 10080401, "force")


    # Column springs
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_1T.out"), "-ele", 10010107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_2T.out"), "-ele", 10010207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_3T.out"), "-ele", 10010307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_4T.out"), "-ele", 10010407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_1B.out"), "-ele", 10020108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_2B.out"), "-ele", 10020208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_3B.out"), "-ele", 10020308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_4B.out"), "-ele", 10020408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_1T.out"), "-ele", 10020107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_2T.out"), "-ele", 10020207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_3T.out"), "-ele", 10020307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_4T.out"), "-ele", 10020407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_1B.out"), "-ele", 10030108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_2B.out"), "-ele", 10030208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_3B.out"), "-ele", 10030308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_4B.out"), "-ele", 10030408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_1T.out"), "-ele", 10030107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_2T.out"), "-ele", 10030207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_3T.out"), "-ele", 10030307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_4T.out"), "-ele", 10030407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_1B.out"), "-ele", 10040108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_2B.out"), "-ele", 10040208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_3B.out"), "-ele", 10040308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_4B.out"), "-ele", 10040408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_1T.out"), "-ele", 10040107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_2T.out"), "-ele", 10040207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_3T.out"), "-ele", 10040307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_4T.out"), "-ele", 10040407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_1B.out"), "-ele", 10050108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_2B.out"), "-ele", 10050208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_3B.out"), "-ele", 10050308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_4B.out"), "-ele", 10050408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_1T.out"), "-ele", 10050107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_2T.out"), "-ele", 10050207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_3T.out"), "-ele", 10050307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_4T.out"), "-ele", 10050407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_1B.out"), "-ele", 10060108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_2B.out"), "-ele", 10060208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_3B.out"), "-ele", 10060308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_4B.out"), "-ele", 10060408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_1T.out"), "-ele", 10060107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_2T.out"), "-ele", 10060207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_3T.out"), "-ele", 10060307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring6_4T.out"), "-ele", 10060407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_1B.out"), "-ele", 10070108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_2B.out"), "-ele", 10070208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_3B.out"), "-ele", 10070308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_4B.out"), "-ele", 10070408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_1T.out"), "-ele", 10070107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_2T.out"), "-ele", 10070207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_3T.out"), "-ele", 10070307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring7_4T.out"), "-ele", 10070407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_1B.out"), "-ele", 10080108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_2B.out"), "-ele", 10080208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_3B.out"), "-ele", 10080308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_4B.out"), "-ele", 10080408, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_1T.out"), "-ele", 10080107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_2T.out"), "-ele", 10080207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_3T.out"), "-ele", 10080307, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring8_4T.out"), "-ele", 10080407, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring9_1B.out"), "-ele", 10090108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring9_2B.out"), "-ele", 10090208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring9_3B.out"), "-ele", 10090308, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring9_4B.out"), "-ele", 10090408, "material", 3, "stressStrain")


    # Beam springs
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_1R.out"), "-ele", 10020109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_2L.out"), "-ele", 10020210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_2R.out"), "-ele", 10020209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_3L.out"), "-ele", 10020310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_3R.out"), "-ele", 10020309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_4L.out"), "-ele", 10020410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_1R.out"), "-ele", 10030109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_2L.out"), "-ele", 10030210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_2R.out"), "-ele", 10030209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_3L.out"), "-ele", 10030310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_3R.out"), "-ele", 10030309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_4L.out"), "-ele", 10030410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_1R.out"), "-ele", 10040109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_2L.out"), "-ele", 10040210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_2R.out"), "-ele", 10040209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_3L.out"), "-ele", 10040310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_3R.out"), "-ele", 10040309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_4L.out"), "-ele", 10040410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_1R.out"), "-ele", 10050109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_2L.out"), "-ele", 10050210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_2R.out"), "-ele", 10050209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_3L.out"), "-ele", 10050310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_3R.out"), "-ele", 10050309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_4L.out"), "-ele", 10050410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_1R.out"), "-ele", 10060109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_2L.out"), "-ele", 10060210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_2R.out"), "-ele", 10060209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_3L.out"), "-ele", 10060310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_3R.out"), "-ele", 10060309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring6_4L.out"), "-ele", 10060410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_1R.out"), "-ele", 10070109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_2L.out"), "-ele", 10070210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_2R.out"), "-ele", 10070209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_3L.out"), "-ele", 10070310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_3R.out"), "-ele", 10070309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring7_4L.out"), "-ele", 10070410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_1R.out"), "-ele", 10080109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_2L.out"), "-ele", 10080210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_2R.out"), "-ele", 10080209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_3L.out"), "-ele", 10080310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_3R.out"), "-ele", 10080309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring8_4L.out"), "-ele", 10080410, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_1R.out"), "-ele", 10090109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_2L.out"), "-ele", 10090210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_2R.out"), "-ele", 10090209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_3L.out"), "-ele", 10090310, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_3R.out"), "-ele", 10090309, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring9_4L.out"), "-ele", 10090410, "material", 3, "stressStrain")


    # Panel zone springs (if any)
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_1.out"), "-ele", 11020100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_2.out"), "-ele", 11020200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_3.out"), "-ele", 11020300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_4.out"), "-ele", 11020400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_1.out"), "-ele", 11030100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_2.out"), "-ele", 11030200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_3.out"), "-ele", 11030300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_4.out"), "-ele", 11030400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_1.out"), "-ele", 11040100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_2.out"), "-ele", 11040200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_3.out"), "-ele", 11040300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_4.out"), "-ele", 11040400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_1.out"), "-ele", 11050100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_2.out"), "-ele", 11050200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_3.out"), "-ele", 11050300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_4.out"), "-ele", 11050400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ6_1.out"), "-ele", 11060100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ6_2.out"), "-ele", 11060200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ6_3.out"), "-ele", 11060300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ6_4.out"), "-ele", 11060400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ7_1.out"), "-ele", 11070100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ7_2.out"), "-ele", 11070200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ7_3.out"), "-ele", 11070300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ7_4.out"), "-ele", 11070400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ8_1.out"), "-ele", 11080100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ8_2.out"), "-ele", 11080200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ8_3.out"), "-ele", 11080300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ8_4.out"), "-ele", 11080400, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ9_1.out"), "-ele", 11090100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ9_2.out"), "-ele", 11090200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ9_3.out"), "-ele", 11090300, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ9_4.out"), "-ele", 11090400, "material", 1, "stressStrain")
    
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA1_1.out"), "-ele", 11, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA1_4.out"), "-ele", 14, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA2_1.out"), "-ele", 21, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA2_4.out"), "-ele", 24, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA3_1.out"), "-ele", 31, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA3_4.out"), "-ele", 34, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA4_1.out"), "-ele", 41, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA4_4.out"), "-ele", 44, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA5_1.out"), "-ele", 51, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA5_4.out"), "-ele", 54, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA6_1.out"), "-ele", 61, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA6_4.out"), "-ele", 64, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA7_1.out"), "-ele", 71, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA7_4.out"), "-ele", 74, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA8_1.out"), "-ele", 81, "material", 1, "stressStrain")
    ops.recorder("Element", '-file', str(MainFolder/SubFolder/"SMA8_4.out"), "-ele", 84, "material", 1, "stressStrain")

    
    

    # ------------------------------------- Mass -------------------------------------

    # Moment frame mass
    g = 9810.0
    ops.mass(11020104, 12.605, 1.e-9, 1.e-9)
    ops.mass(11020204, 12.605, 1.e-9, 1.e-9)
    ops.mass(11020304, 12.605, 1.e-9, 1.e-9)
    ops.mass(11020404, 12.605, 1.e-9, 1.e-9)

    ops.mass(11030104, 12.397, 1.e-9, 1.e-9)
    ops.mass(11030204, 12.397, 1.e-9, 1.e-9)
    ops.mass(11030304, 12.397, 1.e-9, 1.e-9)
    ops.mass(11030404, 12.397, 1.e-9, 1.e-9)

    ops.mass(11040104, 12.270, 1.e-9, 1.e-9)
    ops.mass(11040204, 12.270, 1.e-9, 1.e-9)
    ops.mass(11040304, 12.270, 1.e-9, 1.e-9)
    ops.mass(11040404, 12.270, 1.e-9, 1.e-9)

    ops.mass(11050104, 12.234, 1.e-9, 1.e-9)
    ops.mass(11050204, 12.234, 1.e-9, 1.e-9)
    ops.mass(11050304, 12.234, 1.e-9, 1.e-9)
    ops.mass(11050404, 12.234, 1.e-9, 1.e-9)

    ops.mass(11060104, 12.134, 1.e-9, 1.e-9)
    ops.mass(11060204, 12.134, 1.e-9, 1.e-9)
    ops.mass(11060304, 12.134, 1.e-9, 1.e-9)
    ops.mass(11060404, 12.134, 1.e-9, 1.e-9)

    ops.mass(11070104, 12.088, 1.e-9, 1.e-9)
    ops.mass(11070204, 12.088, 1.e-9, 1.e-9)
    ops.mass(11070304, 12.088, 1.e-9, 1.e-9)
    ops.mass(11070404, 12.088, 1.e-9, 1.e-9)

    ops.mass(11080104, 12.007, 1.e-9, 1.e-9)
    ops.mass(11080204, 12.007, 1.e-9, 1.e-9)
    ops.mass(11080304, 12.007, 1.e-9, 1.e-9)
    ops.mass(11080404, 12.007, 1.e-9, 1.e-9)

    ops.mass(11090104, 9.803, 1.e-9, 1.e-9)
    ops.mass(11090204, 9.803, 1.e-9, 1.e-9)
    ops.mass(11090304, 9.803, 1.e-9, 1.e-9)
    ops.mass(11090404, 9.803, 1.e-9, 1.e-9)


    # Leaning column mass
    ops.mass(10020500, 264.716, 1.e-9, 1.e-9)
    ops.mass(10030500, 260.335, 1.e-9, 1.e-9)
    ops.mass(10040500, 257.669, 1.e-9, 1.e-9)
    ops.mass(10050500, 256.907, 1.e-9, 1.e-9)
    ops.mass(10060500, 254.812, 1.e-9, 1.e-9)
    ops.mass(10070500, 253.860, 1.e-9, 1.e-9)
    ops.mass(10080500, 252.146, 1.e-9, 1.e-9)
    ops.mass(10090500, 205.869, 1.e-9, 1.e-9)


    # -------------------------------- Eigen analysis --------------------------------

    nEigen = 8
    lambdaN = ops.eigen(nEigen)
    lambda1 = lambdaN[0]
    lambda2 = lambdaN[1]
    lambda3 = lambdaN[2]
    lambda4 = lambdaN[3]
    lambda5 = lambdaN[4]
    lambda6 = lambdaN[5]
    lambda7 = lambdaN[6]
    lambda8 = lambdaN[7]
    w1 = pow(lambda1, 0.5)
    w2 = pow(lambda2, 0.5)
    w3 = pow(lambda3, 0.5)
    w4 = pow(lambda4, 0.5)
    w5 = pow(lambda5, 0.5)
    w6 = pow(lambda6, 0.5)
    w7 = pow(lambda7, 0.5)
    w8 = pow(lambda8, 0.5)
    T1 = round(2.0*pi/w1, 3)
    T2 = round(2.0*pi/w2, 3)
    T3 = round(2.0*pi/w3, 3)
    T4 = round(2.0*pi/w4, 3)
    T5 = round(2.0*pi/w5, 3)
    T6 = round(2.0*pi/w6, 3)
    T7 = round(2.0*pi/w7, 3)
    T8 = round(2.0*pi/w8, 3)
    print(f"T1 = {T1} s")
    print(f"T2 = {T2} s")
    print(f"T3 = {T3} s")

    mode = []
    for i in range(1, NStory + 1):
        mode.append(ops.nodeEigenvector(11020204, i, 1))
        mode.append(ops.nodeEigenvector(11030204, i, 1))
        mode.append(ops.nodeEigenvector(11040204, i, 1))
        mode.append(ops.nodeEigenvector(11050204, i, 1))
        mode.append(ops.nodeEigenvector(11060204, i, 1))
        mode.append(ops.nodeEigenvector(11070204, i, 1))
        mode.append(ops.nodeEigenvector(11080204, i, 1))
        mode.append(ops.nodeEigenvector(11090204, i, 1))
        np.savetxt(MainFolder/SubFolder/f"mode{i}.out", mode)
        if i == 1:
            mode_list = mode.copy()
        mode = []
    with open(MainFolder/SubFolder/"Period.out", "w") as f:
        f.write(f"{T1}\n")
        f.write(f"{T2}\n")
        f.write(f"{T3}\n")
        f.write(f"{T4}\n")
        f.write(f"{T5}\n")
        f.write(f"{T6}\n")
        f.write(f"{T7}\n")
        f.write(f"{T8}\n")


    # --------------------------- Static gravity analysis ----------------------------

    ops.timeSeries("Linear", 100)
    ops.pattern("Plain", 100, 100)

    # Moment frame loads
    ops.load(11020101, 0., -123659.9, 0.)
    ops.load(11020201, 0., -123659.9, 0.)
    ops.load(11020301, 0., -123659.9, 0.)
    ops.load(11020401, 0., -123659.9, 0.)

    ops.load(11030101, 0., -121613.8, 0.)
    ops.load(11030201, 0., -121613.8, 0.)
    ops.load(11030301, 0., -121613.8, 0.)
    ops.load(11030401, 0., -121613.8, 0.)

    ops.load(11040101, 0., -120368.3, 0.)
    ops.load(11040201, 0., -120368.3, 0.)
    ops.load(11040301, 0., -120368.3, 0.)
    ops.load(11040401, 0., -120368.3, 0.)

    ops.load(11050101, 0., -120012.4, 0.)
    ops.load(11050201, 0., -120012.4, 0.)
    ops.load(11050301, 0., -120012.4, 0.)
    ops.load(11050401, 0., -120012.4, 0.)

    ops.load(11060101, 0., -119033.8, 0.)
    ops.load(11060201, 0., -119033.8, 0.)
    ops.load(11060301, 0., -119033.8, 0.)
    ops.load(11060401, 0., -119033.8, 0.)

    ops.load(11070101, 0., -118589.0, 0.)
    ops.load(11070201, 0., -118589.0, 0.)
    ops.load(11070301, 0., -118589.0, 0.)
    ops.load(11070401, 0., -118589.0, 0.)

    ops.load(11080101, 0., -117788.3, 0.)
    ops.load(11080201, 0., -117788.3, 0.)
    ops.load(11080301, 0., -117788.3, 0.)
    ops.load(11080401, 0., -117788.3, 0.)

    ops.load(11090101, 0., -96170.1, 0.)
    ops.load(11090201, 0., -96170.1, 0.)
    ops.load(11090301, 0., -96170.1, 0.)
    ops.load(11090401, 0., -96170.1, 0.)


    # gravity frame loads
    ops.load(10020500, 0., -2596859.2, 0.)
    ops.load(10030500, 0., -2553889.5, 0.)
    ops.load(10040500, 0., -2527734.1, 0.)
    ops.load(10050500, 0., -2520261.2, 0.)
    ops.load(10060500, 0., -2499710.5, 0.)
    ops.load(10070500, 0., -2490369.3, 0.)
    ops.load(10080500, 0., -2473555.1, 0.)
    ops.load(10090500, 0., -2019571.8, 0.)

    ops.wipeAnalysis()
    ops.constraints("Plain")
    ops.numberer("RCM")
    ops.system("BandGeneral")
    ops.test("NormDispIncr", 1.0e-5, 60)
    ops.algorithm("Newton")
    ops.integrator("LoadControl", 0.1)
    ops.analysis("Static")
    ops.analyze(10)
    ops.loadConst("-time", 0.0)


    # ---------------------------- Time history analysis -----------------------------

    MF_FloorNodes = [11020204, 11030204, 11040204, 11050204, 11060204, 11070204, 11080204, 11090204]

    if analysis_type == "TH":
        # Rayleigh damping
        zeta = 0.02
        a0 = zeta * 2.0 * w1 * w3 / (w1 + w3)
        a1 = zeta * 2.0 / (w1 + w3)
        a1_mod = a1 * (1.0 + n) / n
        beam_Ids = [10020111, 10020112, 10020204, 10020311, 10020312, 10030111, 10030112, 10030204, 10030311, 10030312, 10040111, 10040112, 10040204, 10040311, 10040312, 10050111, 10050112, 10050204, 10050311, 10050312, 10060111, 10060112, 10060204, 10060311, 10060312, 10070111, 10070112, 10070204, 10070311, 10070312, 10080111, 10080112, 10080204, 10080311, 10080312, 10090111, 10090112, 10090204, 10090311, 10090312]
        column_Ids = [10010101, 10010201, 10010301, 10010401, 10020101, 10020201, 10020301, 10020401, 10030102, 10030103, 10030202, 10030203, 10030302, 10030303, 10030402, 10030403, 10040101, 10040201, 10040301, 10040401, 10050102, 10050103, 10050202, 10050203, 10050302, 10050303, 10050402, 10050403, 10060101, 10060201, 10060301, 10060401, 10070102, 10070103, 10070202, 10070203, 10070302, 10070303, 10070402, 10070403, 10080101, 10080201, 10080301, 10080401]
        mass_Ids = [11020104, 11020204, 11020304, 11020404, 11020504, 11020604, 11020704, 11020804, 11030104, 11030204, 11030304, 11030404, 11030504, 11030604, 11030704, 11030804, 11040104, 11040204, 11040304, 11040404, 11040504, 11040604, 11040704, 11040804, 11050104, 11050204, 11050304, 11050404, 11050504, 11050604, 11050704, 11050804, 11060104, 11060204, 11060304, 11060404, 11060504, 11060604, 11060704, 11060804, 11070104, 11070204, 11070304, 11070404, 11070504, 11070604, 11070704, 11070804, 11080104, 11080204, 11080304, 11080404, 11080504, 11080604, 11080704, 11080804, 11090104, 11090204, 11090304, 11090404, 11090504, 11090604, 11090704, 11090804, 10020500, 10030500, 10040500, 10050500, 10060500, 10070500, 10080500, 10090500]
        # ops.region(1, "-ele", *beam_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)
        # ops.region(2, "-ele", *column_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)
        # ops.region(3, "-ele", *mass_Ids, "-rayleigh", a0, 0.0, 0.0, 0.0)
        ops.rayleigh(a0, 0.0, a1, 0.0)
        
        # Ground motion acceleration file input
        ops.timeSeries("Path", 200, "-dt", GMdt, "-filePath", GMFile, "-factor", EqSF * g)
        ops.pattern("UniformExcitation", 200, 1, "-accel", 200)
        totalTime = GMduration + FVduration
        MaxAnalysisDrift = 0.5
        result = TimeHistorySolver(GMdt, totalTime, story_height, MF_FloorNodes, CollapseDrift, MaxAnalysisDrift, GMname, maxRunTime, ShowAnimation)
        print(f"Running status: {result[0]}")
        print(f"Control time: {result[1]}")
        print(f"Collapse: {bool(result[2])}")
        for i in range(NStory):
            SDR = result[3][:, i]
            np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")
        np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[4], fmt="%.6f")
        with open(MainFolder/SubFolder/"Status.dat", "w") as f:
            f.write(str(result[0]))

    # ------------------------------ Pushover analysis -------------------------------

    elif analysis_type == "PO":
        m2 = 315.138
        m3 = 309.923
        m4 = 306.749
        m5 = 305.842
        m6 = 303.348
        m7 = 302.214
        m8 = 300.174
        m9 = 245.082

        F2 = m2 * mode_list[0]
        F3 = m3 * mode_list[1]
        F4 = m4 * mode_list[2]
        F5 = m5 * mode_list[3]
        F6 = m6 * mode_list[4]
        F7 = m7 * mode_list[5]
        F8 = m8 * mode_list[6]
        F9 = m9 * mode_list[7]
        ops.timeSeries("Linear", 222)
        ops.pattern("Plain", 222, 222)
        ops.load(11020204, F2, 0.0, 0.0)
        ops.load(11030204, F3, 0.0, 0.0)
        ops.load(11040204, F4, 0.0, 0.0)
        ops.load(11050204, F5, 0.0, 0.0)
        ops.load(11060204, F6, 0.0, 0.0)
        ops.load(11070204, F7, 0.0, 0.0)
        ops.load(11080204, F8, 0.0, 0.0)
        ops.load(11090204, F9, 0.0, 0.0)
        Dmax = maxRoofDrift * Floor9
        Dincr = 0.5
        result = PushoverAnalysis(MF_FloorNodes, story_height, Dmax, Dincr, maxRunTime, ShowAnimation)
        status = result[0]
        roofDisp = result[1]
        print(f"Running status: {status}")
        print(f"Roof displacement: {roofDisp}")
        print(f"Roof drift ratio: {roofDisp / HBuilding}")
        for i in range(NStory):
            SDR = result[2][:, i]
            np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")
        np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[3], fmt="%.6f")
        pattern = np.array([F2, F3, F4, F5, F6, F7, F8, F9])
        np.savetxt(MainFolder/SubFolder/"Pattern.out", pattern, fmt="%.6f")
    # ------------------------------- Cyclic pushover --------------------------------

    elif analysis_type == "CP":

        m2 = 315.138
        m3 = 309.923
        m4 = 306.749
        m5 = 305.842
        m6 = 303.348
        m7 = 302.214
        m8 = 300.174
        m9 = 245.082

        F2 = m2 * mode_list[0]
        F3 = m3 * mode_list[1]
        F4 = m4 * mode_list[2]
        F5 = m5 * mode_list[3]
        F6 = m6 * mode_list[4]
        F7 = m7 * mode_list[5]
        F8 = m8 * mode_list[6]
        F9 = m9 * mode_list[7]
        ops.timeSeries("Linear", 222)
        ops.pattern("Plain", 222, 222)
        ops.load(11020204, F2, 0.0, 0.0)
        ops.load(11030204, F3, 0.0, 0.0)
        ops.load(11040204, F4, 0.0, 0.0)
        ops.load(11050204, F5, 0.0, 0.0)
        ops.load(11060204, F6, 0.0, 0.0)
        ops.load(11070204, F7, 0.0, 0.0)
        ops.load(11080204, F8, 0.0, 0.0)
        ops.load(11090204, F9, 0.0, 0.0)
        CtrlNode = 11090204
        Dincr = 0.5
        result = CyclicPushover(MF_FloorNodes, RDR_path, HBuilding,story_height, Dincr, maxRunTime, ShowAnimation)
        for i in range(len(story_height)):
            SDR = result[2][:, i]
            np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")
        np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[3], fmt="%.6f")

    return result

# ----------------------------- Building information -----------------------------
#
# Moment resisting frame model information
# Frame name: MC8_SMRF
# Generation time: 2025-02-24 19:13:13.698055
# All units are in [N, mm, t]
# 
# 
# --------------- 1. Building Geometry ---------------
# 
# Building height: 35600
# Number of story: 8
# Number of bays: 3
# Plane dimensions [mm]: 45750 x 30500
# Number of moment frames: 2
# External column tributary area [mm]: 9150 x 3050.0
# Internal column tributary area [mm]: 9150 x 3050.0
# 
# 
# --------------- 2. Structural Components ---------------
# 
# Beam sections:
#  Floor  Bay-1  Bay-2  Bay-3
#      2 W24x84 W24x84 W24x84
#      3 W24x84 W24x84 W24x84
#      4 W24x76 W24x76 W24x76
#      5 W24x76 W24x76 W24x76
#      6 W24x55 W24x55 W24x55
#      7 W24x55 W24x55 W24x55
#      8 W21x44 W21x44 W21x44
#      9 W21x44 W21x44 W21x44
# 
# Column sections:
#  Story  Axis-1  Axis-2  Axis-3  Axis-4
#      1 W18x175 W18x192 W18x192 W18x175
#      2 W18x175 W18x192 W18x192 W18x175
#      3 W18x106 W18x192 W18x192 W18x106
#      4 W18x106 W18x192 W18x192 W18x106
#      5  W18x71 W18x143 W18x143  W18x71
#      6  W18x71 W18x143 W18x143  W18x71
#      7  W18x55 W18x119 W18x119  W18x55
#      8  W18x55 W18x119 W18x119  W18x55
# 
# Stories with column splices: 3, 5, 7
# 
# Doubler plate thickness [mm]:
#  Floor  Axis-1  Axis-2  Axis-3  Axis-4
#      2       0       0       0       0
#      3       0       0       0       0
#      4       0       0       0       0
#      5       0       0       0       0
#      6       0       0       0       0
#      7       0       0       0       0
#      8       0       0       0       0
#      9       0       0       0       0
# 
# 
# --------------- 3. Load and Material ---------------
# 
# Material properties:
# 	Young's modulus [MPa]: 206000
# 	Nominal yield strength of beams [MPa]: 345
# 	Nominal yield strength of columns [MPa]: 345
# 	Possion ratio: 0.3
# 
# Load [MPa]:
# Story/Floor         Dead         Live     Cladding
#         1/2 1.000000e-09 1.000000e-09 1.000000e-09
#         2/3 1.000000e-09 1.000000e-09 1.000000e-09
#         3/4 1.000000e-09 1.000000e-09 1.000000e-09
#         4/5 1.000000e-09 1.000000e-09 1.000000e-09
#         5/6 1.000000e-09 1.000000e-09 1.000000e-09
#         6/7 1.000000e-09 1.000000e-09 1.000000e-09
#         7/8 1.000000e-09 1.000000e-09 1.000000e-09
#         8/9 1.000000e-09 1.000000e-09 1.000000e-09
# 
# Load and mass combination coefficients:
#         Dead  Live  Cladding
# Weight  1.05  0.25      1.05
# Mass    1.00  0.00      1.00
# 
# Axial compressive ratio of columns:
# Story       Axis-1       Axis-2       Axis-3       Axis-4
#    1b 7.858677e-07 7.187473e-07 7.187473e-07 7.858677e-07
#    1t 7.858677e-07 7.187473e-07 7.187473e-07 7.858677e-07
#    2b 6.869994e-07 6.283233e-07 6.283233e-07 6.869994e-07
#    2t 6.869994e-07 6.283233e-07 6.283233e-07 6.869994e-07
#    3b 9.728169e-07 5.383382e-07 5.383382e-07 9.728169e-07
#    3t 9.728169e-07 5.383382e-07 5.383382e-07 9.728169e-07
#    4b 8.102071e-07 4.483530e-07 4.483530e-07 8.102071e-07
#    4t 8.102071e-07 4.483530e-07 4.483530e-07 8.102071e-07
#    5b 9.636495e-07 4.795304e-07 4.795304e-07 9.636495e-07
#    5t 9.636495e-07 4.795304e-07 4.795304e-07 9.636495e-07
#    6b 7.216799e-07 3.591217e-07 3.591217e-07 7.216799e-07
#    6t 7.216799e-07 3.591217e-07 3.591217e-07 7.216799e-07
#    7b 6.188855e-07 2.856395e-07 2.856395e-07 6.188855e-07
#    7t 6.188855e-07 2.856395e-07 2.856395e-07 6.188855e-07
#    8b 3.067149e-07 1.415607e-07 1.415607e-07 3.067149e-07
#    8t 3.067149e-07 1.415607e-07 1.415607e-07 3.067149e-07
# 
# Seiemic weight of considered 2D frame: 23430.89 kN
# Seiemic mass of considered 2D frame: 2388.47 t
# 
# 
# --------------- 4. Connection and Boundary Condition ---------------
# 
# Base support: Fixed
# Beam-to-column connection: Reduced beam section (RBS)
# Reduced beam section (RBS) parameters: 0.625, 0.75, 0.25
# Consider panel zone deformation: Yes (Parallelogram)
# 

