# --------------------------------------------------------------------------------
# ----------------------------------- MRF4S_AS -----------------------------------
# -------------------- Generated by: MRFHelper (Version 2.0) ---------------------
# --------------------------------------------------------------------------------

import os
import numpy as np
from pathlib import Path
import openseespy.opensees as ops
from subroutines.BeamHinge import BeamHinge
from subroutines.ColumnHinge import ColumnHinge
from subroutines.PanelZone import PanelZone
from subroutines.Spring_Zero import Spring_Zero
from subroutines.Spring_Rigid import Spring_Rigid
from subroutines.TimeHistorySolver import TimeHistorySolver
from subroutines.PushoverAnalysis import PushoverAnalysis
from subroutines.CyclicPushover import CyclicPushover
from subroutines.DisplayModel2D import DisplayModel2D
from math import pi
from typing import Literal


def run_openseespy(
    maxRunTime: float,
    analysis_type: Literal["TH", "PO", "CP"],
    ShowAnimation: Literal[True, False],
    MPCO: Literal[True, False],
    MainFolder: Path,
    GMname: str,
    SubFolder: Path,
    GMdt: float,
    GMpoints: int,
    GMduration: float,
    FVduration: float,
    EqSF: float,
    GMFile: Path,
    maxRoofDrift: float,
    CollapseDrift: float,
    RDR_path: list[float]
    ):

    ops.wipe()
    ops.model("basic", "-ndm", 2, "-ndf", 3)

    # Basic model variables
    GMFile = GMFile.absolute().as_posix()

    # Results folders
    if not MainFolder.exists():
        os.mkdir(MainFolder)
    if not (MainFolder/SubFolder).exists():
        os.mkdir(MainFolder/SubFolder)

    # Basic parameters
    NStory = 4
    NBay = 2
    E = 206000.00
    mu = 0.3
    fy_beam = 345.00
    fy_column = 345.00
    ops.uniaxialMaterial("Elastic", 9, 1.e-9)
    ops.uniaxialMaterial("Elastic", 99, 1.e12)
    ops.geomTransf("Linear", 1)
    ops.geomTransf("PDelta", 2)
    ops.geomTransf("Corotational", 3)
    A_Stiff = 1.e8
    I_Stiff = 1.e13

    # Building geometry
    Floor1 = 0.0
    Floor2 = 4600.0
    Floor3 = 8300.0
    Floor4 = 12000.0
    Floor5 = 15700.0
    story_height = [4600, 3700, 3700, 3700]

    Axis1 = 0.0
    Axis2 = 9100.0
    Axis3 = 18200.0
    Axis4 = 27300.0

    HBuilding = 15700.0


    # ------------------------------------ Nodes -------------------------------------

    # Support nodes
    ops.node(10010100, Axis1, Floor1)
    ops.node(10010200, Axis2, Floor1)
    ops.node(10010300, Axis3, Floor1)
    ops.node(10010400, Axis4, Floor1)
    
    # Leaning column grid nodes
    ops.node(10020400, Axis4, Floor2)
    ops.node(10030400, Axis4, Floor3)
    ops.node(10040400, Axis4, Floor4)
    ops.node(10050400, Axis4, Floor5)
    
    # Leaning column connected nodes
    ops.node(10020402, Axis4, Floor2)
    ops.node(10020401, Axis4, Floor2)
    ops.node(10030402, Axis4, Floor3)
    ops.node(10030401, Axis4, Floor3)
    ops.node(10040402, Axis4, Floor4)
    ops.node(10040401, Axis4, Floor4)
    ops.node(10050402, Axis4, Floor5)
    
    # Moment frame column nodes
    ops.node(10010101, Axis1, Floor1)
    ops.node(10010201, Axis2, Floor1)
    ops.node(10010301, Axis3, Floor1)

    ops.node(10020102, Axis1, Floor2 - 688.34/2)
    ops.node(10020202, Axis2, Floor2 - 688.34/2)
    ops.node(10020302, Axis3, Floor2 - 688.34/2)

    ops.node(10020101, Axis1, Floor2 + 688.34/2)
    ops.node(10020201, Axis2, Floor2 + 688.34/2)
    ops.node(10020301, Axis3, Floor2 + 688.34/2)

    ops.node(10030102, Axis1, Floor3 - 688.34/2)
    ops.node(10030202, Axis2, Floor3 - 688.34/2)
    ops.node(10030302, Axis3, Floor3 - 688.34/2)

    ops.node(10030101, Axis1, Floor3 + 688.34/2)
    ops.node(10030201, Axis2, Floor3 + 688.34/2)
    ops.node(10030301, Axis3, Floor3 + 688.34/2)

    ops.node(10040102, Axis1, Floor4 - 548.64/2)
    ops.node(10040202, Axis2, Floor4 - 548.64/2)
    ops.node(10040302, Axis3, Floor4 - 548.64/2)

    ops.node(10040101, Axis1, Floor4 + 548.64/2)
    ops.node(10040201, Axis2, Floor4 + 548.64/2)
    ops.node(10040301, Axis3, Floor4 + 548.64/2)

    ops.node(10050102, Axis1, Floor5 - 548.64/2)
    ops.node(10050202, Axis2, Floor5 - 548.64/2)
    ops.node(10050302, Axis3, Floor5 - 548.64/2)

    
    # Moment frame beam nodes
    ops.node(10020104, Axis1 + 311.15, Floor2)
    ops.node(10020205, Axis2 - 311.15, Floor2)
    ops.node(10020204, Axis2 + 311.15, Floor2)
    ops.node(10020305, Axis3 - 311.15, Floor2)

    ops.node(10030104, Axis1 + 311.15, Floor3)
    ops.node(10030205, Axis2 - 311.15, Floor3)
    ops.node(10030204, Axis2 + 311.15, Floor3)
    ops.node(10030305, Axis3 - 311.15, Floor3)

    ops.node(10040104, Axis1 + 303.53, Floor4)
    ops.node(10040205, Axis2 - 303.53, Floor4)
    ops.node(10040204, Axis2 + 303.53, Floor4)
    ops.node(10040305, Axis3 - 303.53, Floor4)

    ops.node(10050104, Axis1 + 303.53, Floor5)
    ops.node(10050205, Axis2 - 303.53, Floor5)
    ops.node(10050204, Axis2 + 303.53, Floor5)
    ops.node(10050305, Axis3 - 303.53, Floor5)

    
    # Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)




    
    # Column splice ndoes
    
    # Beam splice ndoes




    
    
    # ----------------------------------- Elements -----------------------------------

    n = 10.

    # Column elements
    ops.element("elasticBeamColumn", 10010101, 10010101, 10020102, 24903.18, E, (n+1)/n*1673250330.91, 2)
    ops.element("elasticBeamColumn", 10010201, 10010201, 10020202, 24903.18, E, (n+1)/n*1673250330.91, 2)
    ops.element("elasticBeamColumn", 10010301, 10010301, 10020302, 24903.18, E, (n+1)/n*1673250330.91, 2)

    ops.element("elasticBeamColumn", 10020101, 10020101, 10030102, 24903.18, E, (n+1)/n*1673250330.91, 2)
    ops.element("elasticBeamColumn", 10020201, 10020201, 10030202, 24903.18, E, (n+1)/n*1673250330.91, 2)
    ops.element("elasticBeamColumn", 10020301, 10020301, 10030302, 24903.18, E, (n+1)/n*1673250330.91, 2)

    ops.element("elasticBeamColumn", 10030101, 10030101, 10040102, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10030201, 10030201, 10040202, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10030301, 10030301, 10040302, 14451.58, E, (n+1)/n*874085993.76, 2)

    ops.element("elasticBeamColumn", 10040101, 10040101, 10050102, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040201, 10040201, 10050202, 14451.58, E, (n+1)/n*874085993.76, 2)
    ops.element("elasticBeamColumn", 10040301, 10040301, 10050302, 14451.58, E, (n+1)/n*874085993.76, 2)

    
    # Beam elements
    ops.element("elasticBeamColumn", 10020104, 10020104, 10020205, 19354.80, E, (n+1)/n*1506757760.67, 2)
    ops.element("elasticBeamColumn", 10020204, 10020204, 10020305, 19354.80, E, (n+1)/n*1506757760.67, 2)

    ops.element("elasticBeamColumn", 10030104, 10030104, 10030205, 19354.80, E, (n+1)/n*1506757760.67, 2)
    ops.element("elasticBeamColumn", 10030204, 10030204, 10030305, 19354.80, E, (n+1)/n*1506757760.67, 2)

    ops.element("elasticBeamColumn", 10040104, 10040104, 10040205, 17612.87, E, (n+1)/n*861599050.99, 2)
    ops.element("elasticBeamColumn", 10040204, 10040204, 10040305, 17612.87, E, (n+1)/n*861599050.99, 2)

    ops.element("elasticBeamColumn", 10050104, 10050104, 10050205, 17612.87, E, (n+1)/n*861599050.99, 2)
    ops.element("elasticBeamColumn", 10050204, 10050204, 10050305, 17612.87, E, (n+1)/n*861599050.99, 2)


    # Panel zones
    # PanelNone(Floor, Axis, X, Y, E, mu, fy_column, A_stiff, I_stiff, d_col, d_beam, tp, tf, bf, transfTag, type_, position, check=None)
    PanelZone(2, 1, Axis1, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "L")
    PanelZone(2, 2, Axis2, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "I")
    PanelZone(2, 3, Axis3, Floor2, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "R")

    PanelZone(3, 1, Axis1, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "L")
    PanelZone(3, 2, Axis2, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "I")
    PanelZone(3, 3, Axis3, Floor3, E, mu, fy_column, A_Stiff, I_Stiff, 622.30, 688.34, 15.37, 24.38, 327.66, 2, 1, "R")

    PanelZone(4, 1, Axis1, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "L")
    PanelZone(4, 2, Axis2, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "I")
    PanelZone(4, 3, Axis3, Floor4, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "R")

    PanelZone(5, 1, Axis1, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "LT")
    PanelZone(5, 2, Axis2, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "T")
    PanelZone(5, 3, Axis3, Floor5, E, mu, fy_column, A_Stiff, I_Stiff, 607.06, 548.64, 11.18, 17.27, 228.35, 2, 1, "RT")


    # RBS elements (If RBS length equal zero, RBS element will not be generated)





    # Beam hinges
    # BeamHinge(SpringID, NodeI, NodeJ, E, fy_beam, Ix, d, htw, bftf, ry, L, Ls, Lb, My, type_, check=None)
    BeamHinge(10020109, 11020104, 10020104, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10020210, 10020205, 11020202, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10020209, 11020204, 10020204, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10020310, 10020305, 11020302, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)

    BeamHinge(10030109, 11030104, 10030104, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10030210, 10030205, 11030202, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10030209, 11030204, 10030204, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)
    BeamHinge(10030310, 10030305, 11030302, E, fy_beam, 1506757760.67, 688.34, 47.07, 6.02, 54.67, 8477.7, 4238.9, 4238.9, 1724328809.40, 3)

    BeamHinge(10040109, 11040104, 10040104, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10040210, 10040205, 11040202, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10040209, 11040204, 10040204, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10040310, 10040305, 11040302, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)

    BeamHinge(10050109, 11050104, 10050104, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10050210, 10050205, 11050202, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10050209, 11050204, 10050204, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)
    BeamHinge(10050310, 10050305, 11050302, E, fy_beam, 861599050.99, 548.64, 32.31, 4.53, 46.86, 8492.9, 4246.5, 4246.5, 1249431694.68, 3)


    # Column hinges
    # Column(SpringID, NodeI, NodeJ, E, Ix, d, htw, ry, L, Lb, My, PPy, SF_PPy, pinned, check=None)
    ColumnHinge(10010107, 10010100, 10010101, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0824, 1.25, 1)
    ColumnHinge(10010207, 10010200, 10010201, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0549, 1.25, 1)
    ColumnHinge(10010307, 10010300, 10010301, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0824, 1.25, 1)

    ColumnHinge(10020108, 10020102, 11020101, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0824, 1.25, 1)
    ColumnHinge(10020208, 10020202, 11020201, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0549, 1.25, 1)
    ColumnHinge(10020308, 10020302, 11020301, E, 1673250330.91, 622.30, 35.67, 75.38, 4255.83, 4255.83, 2091808719.60, 0.0824, 1.25, 1)

    ColumnHinge(10020107, 11020103, 10020101, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0605, 1.25, 1)
    ColumnHinge(10020207, 11020203, 10020201, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0403, 1.25, 1)
    ColumnHinge(10020307, 11020303, 10020301, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0605, 1.25, 1)

    ColumnHinge(10030108, 10030102, 11030101, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0605, 1.25, 1)
    ColumnHinge(10030208, 10030202, 11030201, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0403, 1.25, 1)
    ColumnHinge(10030308, 10030302, 11030301, E, 1673250330.91, 622.30, 35.67, 75.38, 3011.66, 3011.66, 2091808719.60, 0.0605, 1.25, 1)

    ColumnHinge(10030107, 11030103, 10030101, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0675, 1.25, 1)
    ColumnHinge(10030207, 11030203, 10030201, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0450, 1.25, 1)
    ColumnHinge(10030307, 11030303, 10030301, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0675, 1.25, 1)

    ColumnHinge(10040108, 10040102, 11040101, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0675, 1.25, 1)
    ColumnHinge(10040208, 10040202, 11040201, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0450, 1.25, 1)
    ColumnHinge(10040308, 10040302, 11040301, E, 874085993.76, 607.06, 48.95, 48.75, 3081.51, 3081.51, 1130707416.00, 0.0675, 1.25, 1)

    ColumnHinge(10040107, 11040103, 10040101, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0307, 1.25, 1)
    ColumnHinge(10040207, 11040203, 10040201, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0205, 1.25, 1)
    ColumnHinge(10040307, 11040303, 10040301, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0307, 1.25, 1)

    ColumnHinge(10050108, 10050102, 11050101, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0307, 1.25, 1)
    ColumnHinge(10050208, 10050202, 11050201, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0205, 1.25, 1)
    ColumnHinge(10050308, 10050302, 11050301, E, 874085993.76, 607.06, 48.95, 48.75, 3151.36, 3151.36, 1130707416.00, 0.0307, 1.25, 1)


    # Rigid links
    ops.element("truss", 10020304, 11020304, 10020400, A_Stiff, 99)
    ops.element("truss", 10030304, 11030304, 10030400, A_Stiff, 99)
    ops.element("truss", 10040304, 11040304, 10040400, A_Stiff, 99)
    ops.element("truss", 10050304, 11050304, 10050400, A_Stiff, 99)

    # Leaning column
    ops.element("elasticBeamColumn", 10010401, 10010400, 10020402, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10020401, 10020401, 10030402, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10030401, 10030401, 10040402, A_Stiff, E, I_Stiff, 2)
    ops.element("elasticBeamColumn", 10040401, 10040401, 10050402, A_Stiff, E, I_Stiff, 2)

    # Leaning column hinges
    Spring_Rigid(10020408, 10020402, 10020400)
    Spring_Zero(10020407, 10020400, 10020401)
    Spring_Rigid(10030408, 10030402, 10030400)
    Spring_Zero(10030407, 10030400, 10030401)
    Spring_Rigid(10040408, 10040402, 10040400)
    Spring_Zero(10040407, 10040400, 10040401)
    Spring_Rigid(10050408, 10050402, 10050400)

    # --------------------------------- Constraints ----------------------------------

    # Support
    ops.fix(10010100, 1, 1, 1)
    ops.fix(10010200, 1, 1, 1)
    ops.fix(10010300, 1, 1, 1)
    ops.fix(10010400, 1, 1, 0)

    # Soil constraint
    # (No soil constraint)

    # Rigid diaphragm
    ops.equalDOF(11020204, 11020104, 1)
    ops.equalDOF(11020204, 11020304, 1)

    ops.equalDOF(11030204, 11030104, 1)
    ops.equalDOF(11030204, 11030304, 1)

    ops.equalDOF(11040204, 11040104, 1)
    ops.equalDOF(11040204, 11040304, 1)

    ops.equalDOF(11050204, 11050104, 1)
    ops.equalDOF(11050204, 11050304, 1)


    # ---------------------------------- Recorders -----------------------------------

    # Time
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Time.out"), "-time", "-node", 10010100, "-dof", 1, "disp")

    # Support reactions
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support1.out"), "-node", 10010100, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support2.out"), "-node", 10010200, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support3.out"), "-node", 10010300, "-dof", 1, 2, 3, "reaction")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support4.out"), "-node", 10010400, "-dof", 1, 2, 3, "reaction")

    # Story drift ratio
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR1.out"), "-iNode", 10010100, "-jNode", 11020204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR2.out"), "-iNode", 11020204, "-jNode", 11030204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR3.out"), "-iNode", 11030204, "-jNode", 11040204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR4.out"), "-iNode", 11040204, "-jNode", 11050204, "-dof", 1, "-perpDirn", 2)
    # ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR_Roof.out"), "-iNode", 10010100, "-jNode", 11050204, "-dof", 1, "-perpDirn", 2)

    # Floor acceleration
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA1.out"), "-node", 10010100, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA2.out"), "-node", 11020204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA3.out"), "-node", 11030204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA4.out"), "-node", 11040204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA5.out"), "-node", 11050204, "-dof", 1, "accel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV1.out"), "-node", 10010100, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV2.out"), "-node", 11020204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV3.out"), "-node", 11030204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV4.out"), "-node", 11040204, "-dof", 1, "vel")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV5.out"), "-node", 11050204, "-dof", 1, "vel")

    # Floor displacement
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp1.out"), "-node", 10010100, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp2.out"), "-node", 11020204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp3.out"), "-node", 11030204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp4.out"), "-node", 11040204, "-dof", 1, "disp")
    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp5.out"), "-node", 11050204, "-dof", 1, "disp")

    # Shear forces
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_1.out"), "-ele", 10010101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_2.out"), "-ele", 10010201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear1_3.out"), "-ele", 10010301, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_1.out"), "-ele", 10020101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_2.out"), "-ele", 10020201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear2_3.out"), "-ele", 10020301, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_1.out"), "-ele", 10030101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_2.out"), "-ele", 10030201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear3_3.out"), "-ele", 10030301, "force")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_1.out"), "-ele", 10040101, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_2.out"), "-ele", 10040201, "force")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear4_3.out"), "-ele", 10040301, "force")


    # Column springs
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_1T.out"), "-ele", 10010107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_2T.out"), "-ele", 10010207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring1_3T.out"), "-ele", 10010307, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_1B.out"), "-ele", 10020108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_2B.out"), "-ele", 10020208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_3B.out"), "-ele", 10020308, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_1T.out"), "-ele", 10020107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_2T.out"), "-ele", 10020207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring2_3T.out"), "-ele", 10020307, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_1B.out"), "-ele", 10030108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_2B.out"), "-ele", 10030208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_3B.out"), "-ele", 10030308, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_1T.out"), "-ele", 10030107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_2T.out"), "-ele", 10030207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring3_3T.out"), "-ele", 10030307, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_1B.out"), "-ele", 10040108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_2B.out"), "-ele", 10040208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_3B.out"), "-ele", 10040308, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_1T.out"), "-ele", 10040107, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_2T.out"), "-ele", 10040207, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring4_3T.out"), "-ele", 10040307, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_1B.out"), "-ele", 10050108, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_2B.out"), "-ele", 10050208, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring5_3B.out"), "-ele", 10050308, "material", 3, "stressStrain")


    # Beam springs
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_1R.out"), "-ele", 10020109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_2L.out"), "-ele", 10020210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_2R.out"), "-ele", 10020209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring2_3L.out"), "-ele", 10020310, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_1R.out"), "-ele", 10030109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_2L.out"), "-ele", 10030210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_2R.out"), "-ele", 10030209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring3_3L.out"), "-ele", 10030310, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_1R.out"), "-ele", 10040109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_2L.out"), "-ele", 10040210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_2R.out"), "-ele", 10040209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring4_3L.out"), "-ele", 10040310, "material", 3, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_1R.out"), "-ele", 10050109, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_2L.out"), "-ele", 10050210, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_2R.out"), "-ele", 10050209, "material", 3, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring5_3L.out"), "-ele", 10050310, "material", 3, "stressStrain")


    # Panel zone springs (if any)
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_1.out"), "-ele", 11020100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_2.out"), "-ele", 11020200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ2_3.out"), "-ele", 11020300, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_1.out"), "-ele", 11030100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_2.out"), "-ele", 11030200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ3_3.out"), "-ele", 11030300, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_1.out"), "-ele", 11040100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_2.out"), "-ele", 11040200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ4_3.out"), "-ele", 11040300, "material", 1, "stressStrain")

    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_1.out"), "-ele", 11050100, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_2.out"), "-ele", 11050200, "material", 1, "stressStrain")
    ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ5_3.out"), "-ele", 11050300, "material", 1, "stressStrain")


    # ------------------------------------- Mass -------------------------------------

    # Moment frame mass
    g = 9810.0
    ops.mass(11020104, 16.895, 1.e-9, 1.e-9)
    ops.mass(11020204, 11.263, 1.e-9, 1.e-9)
    ops.mass(11020304, 16.895, 1.e-9, 1.e-9)

    ops.mass(11030104, 16.391, 1.e-9, 1.e-9)
    ops.mass(11030204, 10.927, 1.e-9, 1.e-9)
    ops.mass(11030304, 16.391, 1.e-9, 1.e-9)

    ops.mass(11040104, 16.391, 1.e-9, 1.e-9)
    ops.mass(11040204, 10.927, 1.e-9, 1.e-9)
    ops.mass(11040304, 16.391, 1.e-9, 1.e-9)

    ops.mass(11050104, 14.318, 1.e-9, 1.e-9)
    ops.mass(11050204, 9.545, 1.e-9, 1.e-9)
    ops.mass(11050304, 14.318, 1.e-9, 1.e-9)


    # Leaning column mass
    ops.mass(10020400, 277.864, 1.e-9, 1.e-9)
    ops.mass(10030400, 275.175, 1.e-9, 1.e-9)
    ops.mass(10040400, 275.175, 1.e-9, 1.e-9)
    ops.mass(10050400, 264.121, 1.e-9, 1.e-9)


    # -------------------------------- Eigen analysis --------------------------------

    nEigen = 4
    lambdaN = ops.eigen(nEigen)
    lambda1 = lambdaN[0]
    lambda2 = lambdaN[1]
    lambda3 = lambdaN[2]
    lambda4 = lambdaN[3]
    w1 = pow(lambda1, 0.5)
    w2 = pow(lambda2, 0.5)
    w3 = pow(lambda3, 0.5)
    w4 = pow(lambda4, 0.5)
    T1 = round(2.0*pi/w1, 3)
    T2 = round(2.0*pi/w2, 3)
    T3 = round(2.0*pi/w3, 3)
    T4 = round(2.0*pi/w4, 3)
    print(f"T1 = {T1} s")
    print(f"T2 = {T2} s")
    print(f"T3 = {T3} s")

    mode = []
    for i in range(1, NStory + 1):
        mode.append(ops.nodeEigenvector(11020204, i, 1))
        mode.append(ops.nodeEigenvector(11030204, i, 1))
        mode.append(ops.nodeEigenvector(11040204, i, 1))
        mode.append(ops.nodeEigenvector(11050204, i, 1))
        np.savetxt(MainFolder/SubFolder/f"mode{i}.out", mode)
        if i == 1:
            mode_list = mode.copy()
        mode = []
    with open(MainFolder/SubFolder/"Period.out", "w") as f:
        f.write(f"{T1}\n")
        f.write(f"{T2}\n")
        f.write(f"{T3}\n")
        f.write(f"{T4}\n")


    # --------------------------- Static gravity analysis ----------------------------

    ops.timeSeries("Linear", 100)
    ops.pattern("Plain", 100, 100)

    # Moment frame loads
    ops.load(11020101, 0., -188314.9, 0.)
    ops.load(11020201, 0., -125543.6, 0.)
    ops.load(11020301, 0., -188314.9, 0.)

    ops.load(11030101, 0., -183373.9, 0.)
    ops.load(11030201, 0., -122249.6, 0.)
    ops.load(11030301, 0., -183373.9, 0.)

    ops.load(11040101, 0., -183373.9, 0.)
    ops.load(11040201, 0., -122249.6, 0.)
    ops.load(11040301, 0., -183373.9, 0.)

    ops.load(11050101, 0., -153014.2, 0.)
    ops.load(11050201, 0., -102009.8, 0.)
    ops.load(11050301, 0., -153014.2, 0.)


    # gravity frame loads
    ops.load(10020400, 0., -3205277.0, 0.)
    ops.load(10030400, 0., -3177607.4, 0.)
    ops.load(10040400, 0., -3177607.4, 0.)
    ops.load(10050400, 0., -2856222.8, 0.)

    ops.wipeAnalysis()
    ops.constraints("Plain")
    ops.numberer("RCM")
    ops.system("BandGeneral")
    ops.test("NormDispIncr", 1.0e-5, 60)
    ops.algorithm("Newton")
    ops.integrator("LoadControl", 0.1)
    ops.analysis("Static")
    ops.analyze(10)
    ops.loadConst("-time", 0.0)


    # ---------------------------- Time history analysis -----------------------------

    MF_FloorNodes = [11020204, 11030204, 11040204, 11050204]

    if analysis_type == "TH":
        # Rayleigh damping
        zeta = 0.02
        a0 = zeta * 2.0 * w1 * w3 / (w1 + w3)
        a1 = zeta * 2.0 / (w1 + w3)
        a1_mod = a1 * (1.0 + n) / n
        beam_Ids = [10020104, 10020204, 10030104, 10030204, 10040104, 10040204, 10050104, 10050204]
        column_Ids = [10010101, 10010201, 10010301, 10020101, 10020201, 10020301, 10030101, 10030201, 10030301, 10040101, 10040201, 10040301]
        mass_Ids = [11020104, 11020204, 11020304, 11020404, 11030104, 11030204, 11030304, 11030404, 11040104, 11040204, 11040304, 11040404, 11050104, 11050204, 11050304, 11050404, 10020400, 10030400, 10040400, 10050400]
        # ops.region(1, "-ele", *beam_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)
        # ops.region(2, "-ele", *column_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)
        # ops.region(3, "-ele", *mass_Ids, "-rayleigh", a0, 0.0, 0.0, 0.0)
        ops.rayleigh(a0, 0.0, a1, 0.0)
        
        # Ground motion acceleration file input
        ops.timeSeries("Path", 200, "-dt", GMdt, "-filePath", GMFile, "-factor", EqSF * g)
        ops.pattern("UniformExcitation", 200, 1, "-accel", 200)
        totalTime = GMduration + FVduration
        MaxAnalysisDrift = 0.5
        result = TimeHistorySolver(GMdt, totalTime, story_height, MF_FloorNodes, CollapseDrift, MaxAnalysisDrift, GMname, maxRunTime, ShowAnimation)
        print(f"Running status: {result[0]}")
        print(f"Control time: {result[1]}")
        print(f"Collapse: {bool(result[2])}")
        for i in range(NStory):
            SDR = result[3][:, i]
            np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")
        np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[4], fmt="%.6f")
    
    # ------------------------------ Pushover analysis -------------------------------

    elif analysis_type == "PO":
        m2 = 322.918
        m3 = 318.884
        m4 = 318.884
        m5 = 302.302

        F2 = m2 * mode_list[0]
        F3 = m3 * mode_list[1]
        F4 = m4 * mode_list[2]
        F5 = m5 * mode_list[3]
        ops.timeSeries("Linear", 222)
        ops.pattern("Plain", 222, 222)
        ops.load(11020204, F2, 0.0, 0.0)
        ops.load(11030204, F3, 0.0, 0.0)
        ops.load(11040204, F4, 0.0, 0.0)
        ops.load(11050204, F5, 0.0, 0.0)
        Dmax = maxRoofDrift * Floor5
        Dincr = 0.5
        result = PushoverAnalysis(MF_FloorNodes, story_height, Dmax, Dincr, maxRunTime, ShowAnimation)
        status = result[0]
        roofDisp = result[1]
        print(f"Running status: {status}")
        print(f"Roof displacement: {roofDisp}")
        print(f"Roof drift ratio: {roofDisp / HBuilding}")
        for i in range(NStory):
            SDR = result[2][:, i]
            np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")
        np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[3], fmt="%.6f")
        pattern = np.array([F2, F3, F4, F5])
        np.savetxt(MainFolder/SubFolder/"Pattern.out", pattern, fmt="%.6f")

    # ------------------------------- Cyclic pushover --------------------------------

    elif analysis_type == "CP":

        m2 = 322.918
        m3 = 318.884
        m4 = 318.884
        m5 = 302.302

        F2 = m2 * mode_list[0]
        F3 = m3 * mode_list[1]
        F4 = m4 * mode_list[2]
        F5 = m5 * mode_list[3]
        ops.timeSeries("Linear", 222)
        ops.pattern("Plain", 222, 222)
        ops.load(11020204, F2, 0.0, 0.0)
        ops.load(11030204, F3, 0.0, 0.0)
        ops.load(11040204, F4, 0.0, 0.0)
        ops.load(11050204, F5, 0.0, 0.0)
        CtrlNode = 11050204
        Dincr = 0.5
        result = CyclicPushover(CtrlNode, RDR_path, HBuilding, Dincr, maxRunTime, ShowAnimation)

    return result

# ----------------------------- Building information -----------------------------
#
# Moment resisting frame model information
# Frame name: MRF4S_AS
# Generation time: 2024-08-06 16:03:34.002110
# All units are in [N, mm, t]
# 
# 
# --------------- 1. Building Geometry ---------------
# 
# Building height: 15700
# Number of story: 4
# Number of bays: 2
# Plane dimensions [mm]: 42700 x 30500
# Number of moment frames: 2
# External column tributary area [mm]: 9150 x 3050
# Internal column tributary area [mm]: 6100 x 3050
# 
# 
# --------------- 2. Structural Components ---------------
# 
# Beam sections:
#  Floor   Bay-1   Bay-2
#      2 W27x102 W27x102
#      3 W27x102 W27x102
#      4  W21x93  W21x93
#      5  W21x93  W21x93
# 
# Column sections:
#  Story  Axis-1  Axis-2  Axis-3
#      1 W24x131 W24x131 W24x131
#      2 W24x131 W24x131 W24x131
#      3  W24x76  W24x76  W24x76
#      4  W24x76  W24x76  W24x76
# 
# Stories with column splices: None
# 
# Doubler plate thickness [mm]:
#  Floor  Axis-1  Axis-2  Axis-3
#      2       0       0       0
#      3       0       0       0
#      4       0       0       0
#      5       0       0       0
# 
# 
# --------------- 3. Load and Material ---------------
# 
# Material properties:
# 	Young's modulus [MPa]: 206000
# 	Nominal yield strength of beams [MPa]: 345
# 	Nominal yield strength of columns [MPa]: 345
# 	Possion ratio: 0.3
# 
# Load [MPa]:
# Story/Floor   Dead    Live  Cladding
#         1/2 0.0043 0.00240    0.0012
#         2/3 0.0043 0.00240    0.0012
#         3/4 0.0043 0.00240    0.0012
#         4/5 0.0043 0.00096    0.0012
# 
# Load and mass combination coefficients:
#         Dead  Live  Cladding
# Weight  1.05  0.25      1.05
# Mass    1.00  0.00      1.00
# 
# Axial compressive ratio of columns:
# Story   Axis-1   Axis-2   Axis-3
#    1b 0.082415 0.054944 0.082415
#    1t 0.082415 0.054944 0.082415
#    2b 0.060497 0.040331 0.060497
#    2t 0.060497 0.040331 0.060497
#    3b 0.067469 0.044980 0.067469
#    3t 0.067469 0.044980 0.067469
#    4b 0.030690 0.020460 0.030690
#    4t 0.030690 0.020460 0.030690
# 
# Seiemic weight of considered 2D frame: 14304.92 kN
# Seiemic mass of considered 2D frame: 1262.99 t
# 
# 
# --------------- 4. Connection and Boundary Condition ---------------
# 
# Base support: Fixed
# Beam-to-column connection: Hinged connection
# Consider panel zone deformation: Yes (Parallelogram)
# 

